### ISSUE TITLE
Ability to use npm pkgs / what is the package.json for?

### ISSUE THREAD

**Issue by jameswomack** [stdlib/lib#1]
Hey there! I'm already diggin' this tool:
`f james/twitter/hello sausage bacon eggs`

When I saw package.json I thought I might be able to install packages from there by putting them in package.json, but that doesn't appear to be the case. If not, what should I be using package.json for?

**Comment by keithwhor** [comment]
Just the name right now. `package.json` will be for `node_modules` soon, the functionality isn't ready quite yet. Put on ETA on early next week.

It'll also be for documentation of the function, keywords, permissions, security, etc.

**Comment by oculus42** [comment]
Should all those things be overloaded into the existing idea of `package.json`? Perhaps something like `function.json` would be an appropriate choice for permissions, security, etc on the FaaS platform.

**Comment by keithwhor** [comment]
Perhaps. I don't mind overloading package.json, personally, since we'll need to use shared features anyway. The less files a developer has to manage, the better.

**Comment by keithwhor** [comment]
npm packages are now available by setting `node_modules` in `package.json` the same way you would normally.

note there are limitations: all functions within a namespace share dependencies, so they must all be versioned identically when sharing packages (you'll get an error if they're not), and there's a maximum limit of 5MB for total dependencies size within a namespace.
