### ISSUE TITLE
Support for HTTP POST's on stdlib functions?

### ISSUE THREAD

**Issue by ericnograles** [stdlib/lib#100]
Hi guys,

Sorry if I missed this in the docs, but is there currently to invoke an stdlib function using an HTTP POST, or is it all GET's by convention?

**Comment by jacoblee93** [comment]
Hey Eric,

Yes, you can invoke a function using POST. If you call a StdLib function with a POST request, we will interpret the body of your request as the parameters to the function in accordance with the [FaaSlang spec](https://github.com/faaslang/faaslang).

You can see a (very) simple example here: https://github.com/faaslang/faaslang#what-is-faaslang

**Comment by ericnograles** [comment]
Thanks @jacoblee93, totally missed that!

**Comment by zooshme** [comment]
Hi,

I've been trying to make post requests to a local stdlib service but the context.params object is always emtpy.

Any idea what could be causing it? I'm using Postman to make the requests, setting the Content-Type to application/json and sending the body as a json object.

Thank you

**Comment by jacoblee93** [comment]
@zooshme Could you open a new Github issue for this?

**Comment by zooshme** [comment]
Done https://github.com/stdlib/lib/issues/128
