### ISSUE TITLE
error package.json 

### ISSUE THREAD

**Issue by blondesalad87** [stdlib/lib#102]
Following this demo https://medium.com/slack-developer-blog/build-a-serverless-slack-bot-in-9-minutes-with-node-js-and-stdlib-b993cfa15358

When I go to deploy I'm receiving an Error: Invalid Package.json

Can anyone help?

Here's the JSON Template. I've filled out everything perfectly, but it seems that when I run a JSON formatter that the error has to do with double quotes around the Slack App name?

![1-pxynlgk4aegr2y6iml49og](https://user-images.githubusercontent.com/11529416/32124603-410c9826-bb1d-11e7-8644-c2a944898ad0.png)

**Comment by jacoblee93** [comment]
Hi @blondesalad87,

Can you show me your package.json file?

**Comment by blondesalad87** [comment]
@jacoblee93 sure, here it is:

<img width="634" alt="screen shot 2017-10-27 at 4 11 16 pm" src="https://user-images.githubusercontent.com/11529416/32128305-92e7e948-bb31-11e7-907a-1cdda559cc61.png">

I tried modifying the "build" to "legacy" per a few other templates that I've seen with the change; didn't help.

**Comment by blondesalad87** [comment]
@jacoblee93 Also, I have the author piece removed for now just to maintain the integrity of my the email I"m using :)

**Comment by jacoblee93** [comment]
I was able to reproduce your error -- I believe the problem is the smart quotes around "build": “faaslang” (Mac's TextEdit program replaces normal quotes by default for some reason, see https://apple.stackexchange.com/questions/120486/quotes-problem-in-mavericks-or-textedit). 

Can you try again while replacing them with straight quotes? Let me know.

**Comment by blondesalad87** [comment]
@jacoblee93 Hmm, seems like I'm still getting the same error. Made the change in system preferences and within TextEdit. Furthermore, I also got rid of the smart dashes and made the changes across all JSON files. Re-started terminal and nada. Could it possibly be something else?

**Comment by blondesalad87** [comment]
@jacoblee93 any other ideas?

**Comment by jacoblee93** [comment]
Sorry about the delayed response!

Can you try running `lib http` from the same directory?

**Comment by blondesalad87** [comment]
No worries. Ran lib http and got the same error. Screengrab.

<img width="566" alt="screen shot 2017-10-30 at 5 10 48 pm" src="https://user-images.githubusercontent.com/11529416/32201637-61db6b0c-bd95-11e7-9c26-4c5e469b5856.png">

**Comment by jacoblee93** [comment]
Aha. You have to run commands like `lib http` `lib up dev` etc. from the directory containing your service. So in your case, run `cd adooreck/slack-app` or something similar, then try running `lib up dev`.

Let me know if that helps!

**Comment by blondesalad87** [comment]
Thanks! Almost there, but looks like there is still an issue with the JSON. 

<img width="574" alt="screen shot 2017-10-30 at 5 18 47 pm" src="https://user-images.githubusercontent.com/11529416/32201898-7bdef856-bd96-11e7-8fa4-439f893b3dc3.png">

**Comment by jacoblee93** [comment]
Can you show me your `env.json` (with sensitive variables cleared)?

**Comment by blondesalad87** [comment]
<img width="635" alt="screen shot 2017-10-30 at 5 24 25 pm" src="https://user-images.githubusercontent.com/11529416/32202031-35e55830-bd97-11e7-989f-75f7fd17c5c5.png">

**Comment by jacoblee93** [comment]
I see more smart quotes around the value of `SLACK_APP_NAME` - can you try changing those too?

**Comment by blondesalad87** [comment]
BOOM! Success. Looks like the devil is in the details. Thanks so much Jacob!

**Comment by jacoblee93** [comment]
Glad it's working! Let me know if I can help further.
