### ISSUE TITLE
Feat req: more flexible scheduling

### ISSUE THREAD

**Issue by ErikAndreas** [stdlib/lib#103]
The ui interface only allows for fairly simple scheduling. It would be nice if scheduling could be done as CRON or Rate expressions (Azure functions, Aws lamda and Webtask all have it...)

**Comment by keithwhor** [comment]
Hey @ErikAndreas : I agree, we should provide for more flexible scheduling. I'll tag @jacoblee93 and @notoriaga who will be handling this, and they can keep you up to date on progress. I've added it to our official internal roadmap. :)

**Comment by ErikAndreas** [comment]
Hi
any update on this? 

Is the "official internal", or any other, roadmap publicly available somewhere (url)?

**Comment by jacoblee93** [comment]
Hey Andreas,

Expect it done by early next week, if not sooner! Apologies for the delay.

We don't have any publicly available roadmap right now, but we could
discuss making one available in the future.

Best,

Jacob

**Comment by jacoblee93** [comment]
Cron expressions are now supported in scheduled tasks. See http://docs.stdlib.com/main/#/scheduled-tasks for information on syntax. 

For now, you'll have to create these via the Scheduled Tasks section of your StdLib dashboard (https://dashboard.stdlib.com/dashboard). CLI support coming soon.

**Comment by keithwhor** [comment]
Closing! :)
