### ISSUE TITLE
When behind proxy `lib create` doesn't work

### ISSUE THREAD

**Issue by alber70g** [stdlib/lib#104]
It seems that I'm not able to do `lib create` behind a proxy. I've setup HTTP_PROXY env vars but it doesn't work. How to enable the use of a proxy in the command line interface.

The error I get is: `Error: Server unavailable`

Is there a way to get a more verbose error log?

**Comment by keithwhor** [comment]
Hey @Alber70g: Thank you so much for your patience here, I know it's taken me a while to respond. 🙏

Can you let me know what proxy software you're using? I can definitely look into more verbose error reporting on connection failures.

**Comment by keithwhor** [comment]
Closing this -- if you can give more feedback as to proxy / etc., we can look into again. :)

**Comment by alber70g** [comment]
I'm using CNTLM as an intermediate proxy.
