### ISSUE TITLE
Comments must be right above exports

### ISSUE THREAD

**Issue by NicholasLYang** [stdlib/lib#107]
Not actually a bug, more of a confusing error message. When I put code in between the annotations and the exports, like so:
```
/**
* A basic Hello World function
* @param {string} code Code you're writing to a file
* @returns {string}
*/
const fs = require('fs');
module.exports = (code, context, callback) => {
```
I get the following error:

> First parameter can not be of type "Any" or "Object"
> This restriction is intended to reduce end-user confusion around your API,
> if a function is called using only an Object, its properties map to function parameters

**Comment by keithwhor** [comment]
Hey Nicholas,

We're (finally) catching up on backlog. This is actually part of the https://github.com/faaslang/faaslang/ specification and we don't have intention of changing behavior at this point. Allowing function definitions anywhere opens up too much surface area for confusion or bugs; the recommended approach is to just move your imports to the top of the file. :)

**Comment by ocxo** [comment]
I think I had the same error. Ran into this and was confused because I didn't have any code executing, between the annotations and the export. It was just commented out:

```js
/**
* hello
*
* @param {string} user The user id of the user that invoked this command (name is usable as well)
* @param {string} channel The channel id the command was executed in (name is usable as well)
* @param {string} text The text contents of the command
* @param {object} command The full Slack command object
* @param {string} botToken The bot token for the Slack bot you have activated
* @returns {object}
*/
//module.exports = (text = '', command = {}, botToken = null, callback) => { 
//  this commented block causes errors
//  callback(null, {
//    text: `hello`
//  });
//}
module.exports = (user, channel, text = '', command = {}, botToken = null, callback) => {
...
```
