### ISSUE TITLE
Unicode gets mangled

### ISSUE THREAD

**Issue by anishkny** [stdlib/lib#108]
If return string contains Unicode, it works fine locally and in curl, but gets mangled when viewed in the browser: 

URL: https://anishkny.lib.id/hello@0.0.1/
Renders in browser as: "à¤¨à¤®à¤¸à¥à¤¤à¥‡ world"

Details:
```bash
$ cat functions/__main__.js
/**
* A basic Hello World function
* @param {string} name Who you're saying hello to
* @returns {string}
*/
module.exports = async (name = 'world', context) => {
  return `नमस्ते ${name}`;
};

$ lib .
"नमस्ते world"

$ curl https://anishkny.lib.id/hello@0.0.1/
"नमस्ते world"
```

**Comment by anishkny** [comment]
While the team fixes this, here's a workaround:

```
/**
* A basic Hello World function
* @param {string} name Who you're saying hello to
* @returns {string}
*/
module.exports = (name = 'world', context, callback) => {
  return callback(null, `नमस्ते ${name}`,
    {'Content-Type': 'application/json; charset=utf-8'});
};
```

**Comment by PEZ** [comment]
Possibly related. The tutorial slack bot, from here: https://medium.com/slack-developer-blog/build-a-serverless-slack-bot-in-9-minutes-with-node-js-and-stdlib-b993cfa15358

Has a message event handler that looks like so:

```js
module.exports = (user, channel, text = '', event = {}, botToken = null, callback) => {

  // Only send a response to certain messages
  if (text.match(/hey|hello|hi|sup/i)) {
    callback(null, {
      text: `Hey there! <@${user}> said ${text}`
    });
  } else {
    callback(null, {});
  }

};
```

And it triggers on this message text: `@jon jag är ju den enda här som varit medlem i ett riktigt arbetarförbund :D`

**Comment by keithwhor** [comment]
Hey @anishkny: I think you brought this up in Slack, but I don't see this problem using Chrome `63.0.3239.132`. It's my understanding that based on the JSON spec, `application/json` should *always* be utf-8 and not require a charset, meaning this is likely a browser issue.

**Comment by anishkny** [comment]
Yup can repro in `Safari Version 11.0.2 (12604.4.7.1.4)` but *not* in `Chrome Version 63.0.3239.132`. Thanks for following up.
