### ISSUE TITLE
Can't run a lib function in zsh

### ISSUE THREAD

**Issue by sky-admin** [stdlib/lib#111]
![image](https://user-images.githubusercontent.com/6292668/33248656-0ab71be6-d361-11e7-9b39-e018a0ff342f.png)
lib installed success, and create a function 'helloword', and up dev. but cant run remote in zsh. but can run it in bash, why?
![image](https://user-images.githubusercontent.com/6292668/33248704-561aa076-d361-11e7-92f1-7e52e2af3bf4.png)

**Comment by keithwhor** [comment]
You’ll need to add a backslash before the brackets ([, ]) when working in zsh.

Let me know if that helps!

- Keith

**Comment by sky-admin** [comment]
@keithwhor it works, thx!
