### ISSUE TITLE
Can't pass on boolean value in the online task scheduler

### ISSUE THREAD

**Issue by edipetres** [stdlib/lib#112]
When a boolean parameter is required in setting up the task schedule, the form will not accept any input for the boolean value field. (Tried `true, yes, True...`) 
It can also not be left blank, so scheduling a task with a boolean parameter cannot be submitted.

**Comment by jacoblee93** [comment]
Should be fixed, let me know if you run into any other difficulties!

**Comment by jacoblee93** [comment]
Should be fixed, let me know if you run into any other difficulties!

**Comment by jacoblee93** [comment]
You should use `true` and `false` in the boolean field also.

**Comment by edipetres** [comment]
It works great with the dropdown now. Thanks for the quick fix!
