### ISSUE TITLE
Cannot set get parameter in post request

### ISSUE THREAD

**Issue by hanabi1224** [stdlib/lib#113]
I think this is something stdlib should allow. Take slack bot as example, if I have different named functionality set (or even different bot) for bots, the only way to specify it is via get parameter because I cannot change postback data of the webhook,  creating and maintaining 2 different api endpoint is not preferable way for my case

**Comment by keithwhor** [comment]
Hey @hanabi1224: Can you give me a real-world example of your use case? I'm open to exploring this but it also opens up edge cases and potential for confusion / weird usage.

**Comment by keithwhor** [comment]
Hey @hanabi1224 -- I'm going to close this right now, but if you can give an example of your use case happy to re-open and reconsider.
