### ISSUE TITLE
Unable to read file id in file_created event

### ISSUE THREAD

**Issue by whizkidsrise** [stdlib/lib#119]
Hi,
I added new event handler file_created. The event handler is working fine. But I am unable to retrieve file id or any other file parameters. I am getting it as "undefined". What could be the problem in my code? Here is my code.

const lib = require('lib')({token: process.env.STDLIB_TOKEN});
/**
* file_created event
*
*   See https://api.slack.com/events-api for more details.
*
* @param {string} channel The channel id the event was executed in (name is usable as well)
* @param {object} file object
* @param {object} event The full Slack event object
* @param {string} botToken The bot token for the Slack bot you have activated
* @returns {object}
*/
module.exports = (channel, file = {}, event = {}, botToken = null, callback) => {

	
  callback(null, {
    response_type: 'in_channel',
    text: `Hello <@${file.id}>, thanks for loading a file: ` 
  });

};

Here is the output

![image](https://user-images.githubusercontent.com/25928172/34278745-9b52c41c-e661-11e7-9de0-c4fb56a59326.png)

**Comment by jacoblee93** [comment]
You won't receive a `file` param, the file info is probably in the `event` param. You can try logging the `event` param you receive: http://docs.stdlib.com/main/#/creating-services/logging

**Comment by jacoblee93** [comment]
Also, I think it might be better to continue these discussions in our Slack channel - you can get an invite from https://stdlib.com by clicking the button under the community tab :)
