### ISSUE TITLE
Cannot get Slack slash commands working

### ISSUE THREAD

**Issue by edipetres** [stdlib/lib#120]
Have followed the tutorial on medium with the template Slack app, double checked for authorization and links to be correct, are able to trigger the functions manually but Slack will keep throwing an error saying `Darn - that slash command didn't work (error message: `400_client_error`). Manage the command at Test App.`
Since the requests don't even seem to reach my /hello function from Slack I don't see a way as how to debug this.
If you have any input on this it'd be much appreciated. Followed step by step the[tutorial](https://medium.com/slack-developer-blog/build-a-serverless-slack-bot-in-9-minutes-with-node-js-and-stdlib-b993cfa15358) so it might signal a larger issue.

**Comment by jacoblee93** [comment]
Hey @edipetres,

Do events work?

If you're able to trigger the endpoint manually, is it possible that you've put the url into slack wrong? Could you show me the exact link either here or via joining our slack channel (invite link is under community tab at https://stdlib.com).
