### ISSUE TITLE
Support for private repo dependancies

### ISSUE THREAD

**Issue by civocr** [stdlib/lib#122]
I have a few internal dependancies which are private repos on github. I've added them to package.json but fails on lib up dev

>  Server Error: There was a problem installing your dependencies
>  Error: There was an error processing your request

I'm using github's token auth so no need to upload a signing key.

    "b-config": "git+https://<token here>:x-oauth-basic@github.com/myuser/config-component-node.git",

    "b-database": "git+https://<token here>:x-oauth-basic@github.com/myuser/database-component-node.git",

    "b-util": "git+https://<token here>:x-oauth-basic@github.com/myuser/util-component-node.git"`

It would awesome if stdlib could support private repos otherwise I'd need to replicate a lot of my internal shared frameworks to get it to work with stdlib

**Comment by keithwhor** [comment]
Hey @civocr! You caught us at a good time. @jacoblee93 is the lead on our build engine and can keep you up to date. This is a *must have* so you can expect this soon.

**Comment by civocr** [comment]
hey guys, 

just wanted to check in to see how this was progressing and if there was a eta on release?

**Comment by jacoblee93** [comment]
Hi Paul,

We've been quite busy, but I hope to have time to look at this within the next two weeks.

Jacob

**Comment by jacoblee93** [comment]
Hi @civocr,

I'm making this my next priority, I'm aiming to have it done by this Tuesday.

Jacob

**Comment by jacoblee93** [comment]
@civocr, this is now supported :) Use the same format you used above in your initial post.

**Comment by civocr** [comment]
@jacoblee93 is there anything special I need to do before hand?

[11:33:28] $ lib up dev -d
2018/02/15 01:03:54.315 [civocr/bianca] Uploading... 65.79%
2018/02/15 01:03:54.315 [civocr/bianca] Uploading... 100.00%
2018/02/15 01:03:54.757 [civocr/bianca] Authenticated as "civocr" <email@address>!
2018/02/15 01:03:54.757 [civocr/bianca] Compiling package with environment "dev"...
2018/02/15 01:03:54.757 [civocr/bianca] Extracting package contents (size 42032)...
2018/02/15 01:03:54.782 [civocr/bianca] Installing package dependencies...
2018/02/15 01:03:56.217 [civocr/bianca] Server Error: There was a problem installing your dependencies
Error: There was an error processing your request, try logging in again.

**Comment by jacoblee93** [comment]
Hmm the format you have looks good. It's possible that one of your git repos has a dependency on a static binary? We don't support every package with those dependencies yet. 

It could also be a size issue - how large is your node_modules file?

Would you be willing to message me your repo privately so I could try to repro your issue?

**Comment by civocr** [comment]
I've added you to the repo I'm working with

**Comment by jacoblee93** [comment]
Thanks! I'll give it a look and get back to you by tomorrow.

**Comment by jacoblee93** [comment]
Ok, the issue was caused by one of your git dependencies' dependencies formatted as `git+http://<url>` rather than `https`. I've pushed a fix that parses `http` as a valid git url as well, let me know if it works for you!

**Comment by jacoblee93** [comment]
OK, updated things again! One of your dependencies required a package that it didn't have explicitly saved as a dependency, which was causing an issue. Things should work now though.

I had a timeout issue with one of the packages you're using, but that could be because I wasn't using it properly. Let me know if things are working as intended for you!
