### ISSUE TITLE
lib.cli doesn't parse a string starting with a dash (-) properly

### ISSUE THREAD

**Issue by NotWoods** [stdlib/lib#127]
```
async function create_user(tag, name) {
  console.log(tag)
  console.log(name)
}
```
```
> lib .create_user --tag "-KyyGUMA6nuFs9lkHGxg" --name "Tiger"

Tiger
```
```
> lib .create_user --tag "\-KyyGUMA6nuFs9lkHGxg" --name "Tiger"
\-KyyGUMA6nuFs9lkHGxg
Tiger
```

Note: the HTTP interface works with the dash character. Most likely the command line parses the dash as another parameter like `--tag`.

**Comment by keithwhor** [comment]
Yep, I believe that's what's happening. I can look into this. 👍

**Comment by keithwhor** [comment]
This is fixed as of:
https://github.com/keithwhor/cmnd/commit/0f5412ad68c0ebed1a1af5d063227d22bc59dc19

And:
https://github.com/stdlib/lib/commit/5ca36004e6cdf33a77fb6f49c023e0e6f85a8ad0

Hope that helps! :)

**Comment by keithwhor** [comment]
Oops. I should mention;

The fix for this is to do:

```
$ lib user.service[@env] --param="-value"
```

The old way will still work, but if a parameter begins with a dash (or multiple dashes) this is the method you should use. Cheers!
