### ISSUE TITLE
Context.params empty on post requests

### ISSUE THREAD

**Issue by zooshme** [stdlib/lib#128]
Hi,

I've been trying to make post requests to a local stdlib service but the context.params object is always emtpy.

Any idea what could be causing it? I'm using Postman to make the requests, setting the Content-Type to application/json and sending the body as a json object.

Thank you

**Comment by keithwhor** [comment]
Hey @zooshme: can you explain *exactly* how to recreate your error? This shouldn't be happening but I'd like to see if we can replicate it ourselves.

Cheers,
- Keith

**Comment by keithwhor** [comment]
Closing this - let me know if you encounter this issue again and I'll re-open.
