### ISSUE TITLE
Responding with errors using async await

### ISSUE THREAD

**Issue by Chinaski1979** [stdlib/lib#131]
Whenever I try to respond with an error using async await, browser interprets response as successful.

For instance if I do this:

```
module.exports = (paramA = '', paramB = '', context, callback) => {
    return lib[`${context.service.identifier}.add`]({a: a, b: b}, (err, result) => {
        if (err) {
            return callback(err);
        }
        return callback(result);
    });
};
```
It's there's an error its response would be something like:

```
{data: {…}, status: 403, statusText: "Forbidden", headers: {…}, config: {…}}
config
:{headers: {…}, timeout: 0, transformRequest: Array(1), transformResponse: Array(1), baseURL: "http://localhost:8170/chinaski/", …}
data: {error: {…}}
headers: {access-control-allow-origin: "*", access-control-allow-headers: "", content-type: application/json"}
status: 403
statusText: "Forbidden"
```
Which is ideal. And that's because I'm able to specify an error with the callback(). But I can seem to accomplish the same result with async/await. It will always send the response as status code 200.
Is there a way to make explicit that an error is being sent? Using async/await means you have to get rid of the callback param but then it limits the ability to return an error.

```
module.exports = async (paramA) => {
    try {
        const result = await someAsyncOperation(paramA);
        return result;
    } catch (err) {
        return err
    }
};
```

**Comment by keithwhor** [comment]
Hey! So, you shouldn't respond with an error. Uncaught errors will propagate as API errors without needing to be returned. (i.e. you don't need the try / catch statement unless you want to catch an error and throw your own custom error).

I hope that helps! :)
