### ISSUE TITLE
file access when trying to run server

### ISSUE THREAD

**Issue by akul-goyal** [stdlib/lib#133]
Files located outside the server folder cannot be accessed. 
The following command: 

lib . file:~{PATH TO FILE} -d

does not work. 

Only works if the file is located inside of the same folder as the service.
So the command:

lib . file:./{FILENAME} -d

would work.

**Comment by jacoblee93** [comment]
This seems to be isolated to using the `~` character -- relative paths and absolute paths starting with a slash work. The native fs method in Node doesn't support it by default but bash does.

**Comment by keithwhor** [comment]
@jacoblee93 Can you push a new version of this PR with a Windows-specific fix as well?
