### ISSUE TITLE
no way to set content-type header when using async-await

### ISSUE THREAD

**Issue by shahidcodes** [stdlib/lib#135]
```javascript
/**
* A basic Hello World function
* @param {string} link of series
* @param {number} start start episode number
* @param {number} end end episode
* @returns {string}
*/
module.exports = async (link, start=0, end=null, context) => {

  let jsonlink = await fetchLinks(link, start, end);
  let response = jsonlink.reduce((acc, curr)=>{
    return acc + "\n" + curr.file
  }, "")
  return response;
};
```

browser interpret as string thus i also get `\n` in the string where I need to return links in each line. 
P.S I strongly want to use async-await. The code only shows simple use case.

**Comment by keithwhor** [comment]
Hey @sh4hidkh4n! You want to return an HTML doc?

If this is being used as an API, I strongly suggest just returning an `{array}` type, but if you'd really like this to be plaintext readable you can the following:

```javascript
/**
* A basic Hello World function
* @param {string} link of series
* @param {number} start start episode number
* @param {number} end end episode
* @returns {object.http}
*/
module.exports = async (link, start=0, end=null, context) => {

  let jsonlink = await fetchLinks(link, start, end);
  let response = jsonlink.reduce((acc, curr)=>{
    return acc + "\n" + curr.file
  }, "")
  return {
    headers: {'content-type': 'text/plain'}, // or 'text/html' 
    body: new Buffer(response)
  };
};
```

The `object.http` type definition was added in FaaSlang https://github.com/faaslang/faaslang/ about a week ago and allows you to return HTTP responses while using async / await. :)

Hope that helps!

**Comment by shahidcodes** [comment]
Thanks it worked.
