### ISSUE TITLE
Unable to create a scheduled task

### ISSUE THREAD

**Issue by TSedlar** [stdlib/lib#137]
I'm trying to create a task, as the documentation says:
`lib tasks:create disassemble-blog`

But end up simply getting an error while trying to do so:

```
C:\Users\Tyler\AppData\Roaming\nvm\v8.0.0\node_modules\lib.cli\cli\commands\tasks\create.js:87
    if (!selectedService.definitions_json[functionName]) {
                        ^

TypeError: Cannot read property 'definitions_json' of undefined
    at resource.request.index (C:\Users\Tyler\AppData\Roaming\nvm\v8.0.0\node_modules\lib.cli\cli\commands\tasks\create.js:87:25)
    at IncomingMessage.res.on.on (C:\Users\Tyler\AppData\Roaming\nvm\v8.0.0\node_modules\lib.cli\node_modules\api-res\module.js:181:22)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

I have also installed the module globally, like the documentation suggests:
`npm install lib.cli -g`

As the log suggests, I am using node version 8.0.0 which has been installed through [nvm](https://github.com/creationix/nvm)

I tried prior with node version 9.0.0, but it also had the same error. I rolled back to 8.0.0 just in case since the documentation says it supports node versions 7.x and 8.x

I also have the .js file as a function

![](https://i.imgur.com/X1HkjmB.png)

**Comment by jacoblee93** [comment]
Hi @TSedlar,

You'll want to have the third argument on your command line there as your service identifier --
 something like `sedarity.test-service[@<service environment>]` rather than using the function itself. You can set the function within your service you would like to run via the prompts afterwards.

We should definitely have a less confusing error message though! Let me know if that works for you.

Jacob

**Comment by TSedlar** [comment]
@jacoblee93 I seem to be getting the same error running 

`lib tasks:create sedarity.test-service@dev`

It looks like from what I'm reading in the docs, the service has to be deployed to released.
I currently only have it deployed to @dev, so that may be my issue.

**Comment by jacoblee93** [comment]
It should work with a dev service actually, can you try it with the brackets as well? So like:

`lib tasks:create sedarity.test-service[@dev]`

If you're using z-shell, you'll need a backslash before each bracket.

**Comment by TSedlar** [comment]
@jacoblee93 I tried just in case, but it didn't work. It only worked with a service deployed to released, but that's fine, thank you!
