### ISSUE TITLE
Error: There was an error processing your request, try logging in again.

### ISSUE THREAD

**Issue by Loruz** [stdlib/lib#138]
Hello, nice tool. But I can't **lib up dev** or **lib release** simple hello world example.
I just did all steps from **Quickstart** documentation.

- `Preiksas:pdf-micro vytautaspreiksaitis$ lib .
- "hello world"
- Preiksas:pdf-micro vytautaspreiksaitis$ lib up dev
- [preiksas/pdf-micro] Uploading... 100.00%
- [preiksas/pdf-micro] Authenticated as "preiksas" <vpreiks@gmail.com>!
- [preiksas/pdf-micro] Compiling package with environment "dev"...
-  [preiksas/pdf-micro] Extracting package contents (size 606)...
- [preiksas/pdf-micro] Installing package dependencies...
- [preiksas/pdf-micro] Server Error: There was a problem installing your dependencies
- Error: There was an error processing your request, try logging in again.`

I changed nothing by myself , just trying to launch boilerplate code. Dont mind **pdf-micro** name

**Comment by jacoblee93** [comment]
Hey @Loruz! Thanks for bringing this to my attention. I'm looking into this now and will have an update for you shortly.

**Comment by jacoblee93** [comment]
@Loruz, should be good now, let me know if this resurfaces

**Comment by Loruz** [comment]
Yep, it works now, thanks for lightning fast response!
