### ISSUE TITLE
Issue with webpass-service database

### ISSUE THREAD

**Issue by Prithivraj200** [stdlib/lib#139]
HI,

   I am trying to connect database by using webpass-services.database API. But when I try to connect by clicking on connect method given in API, I am getting below error.
   `{
  "error": {
    "type": "RuntimeError",
    "message": "Critical Error: TypeError: Converting circular structure to JSON\n    at JSON.stringify ()\n    at Domain.criticalExecution.run ([eval]:86:45)\n    at Domain.run (domain.js:242:14)\n    at callback ([eval]:66:23)\n    at func.index.apply.params.concat ([eval]:199:51)\n    at MongoClient.connect (/var/task/functions/connect.js:20:12)\n    at args.push (/var/task/node_modules/mongodb/lib/utils.js:404:72)\n    at /var/task/node_modules/mongodb/lib/mongo_client.js:271:5\n    at connectCallback (/var/task/node_modules/mongodb/lib/mongo_client.js:950:5)\n    at /var/task/node_modules/mongodb/lib/mongo_client.js:824:13"
  }
}`

Kindly help me to connect with database

**Comment by jacoblee93** [comment]
Hi @Prithivraj200,

Happy to help! Can you show me what arguments you are passing into your storage function? Also, how are you connecting to the database? Are you using an npm package?

From the error, it seems that you have a circular reference in whatever JSON you are passing in, see:
https://stackoverflow.com/questions/4816099/chrome-sendrequest-error-typeerror-converting-circular-structure-to-json

Best,

Jacob

**Comment by Prithivraj200** [comment]
Hey Jacob,
    
     PFA
![stdlib](https://user-images.githubusercontent.com/22617738/37412895-d9be93ec-27cb-11e8-9de1-949b40b93ef2.png)

**Comment by jacoblee93** [comment]
Can you show me exactly how you're connecting to the database in code? 

If it's more comfortable for you, you can join our Slack channel using the invite link on our site (under the community tab while you're logged in) and direct message me there :) Or shoot me an email: (jacob at stdlib.com)
