### ISSUE TITLE
server unavailable

### ISSUE THREAD

**Issue by pradeepmandalapu** [stdlib/lib#140]
![stdlib](https://user-images.githubusercontent.com/9839380/37639550-e43be11a-2c37-11e8-860a-8ab74681db07.PNG)
HI,
I am trying to do as per documentation. If i type any lib command it gives me error saying that server unavailable.

**Comment by jacoblee93** [comment]
Hey @pradeepmandalapu!

Can I ask for your geolocation and whether you're behind a proxy? We've encountered issues with setups like that before, and it would help us diagnose your problem.

Jacob

**Comment by pradeepmandalapu** [comment]
Yes i am in behind proxy.

**Comment by jacoblee93** [comment]
Ah, it's probable that the proxy is blocking calls to StdLib. Is it possible for you to temporarily disable the proxy?

**Comment by pradeepmandalapu** [comment]
It is not possible. Is there any alternate way to do? Thanks for your quick reply.

**Comment by jacoblee93** [comment]
Is there any way you can add certain hostnames to an whitelist or something similar? And no problem, I'm happy to help!

**Comment by justinzw** [comment]
@pradeepmandalapu you might be able to use an online IDE like https://c9.io. 

It works in your browser and there's a terminal and code editor where you can run the commands.

**Comment by mgollmer** [comment]
Hey there,

same issue here. Is there anykind of solution?
