### ISSUE TITLE
Function works in localhost. Not in dev or release versions.

### ISSUE THREAD

**Issue by Chinaski1979** [stdlib/lib#142]
Whenever I test my function with lib http it works perfectly. However when I run lib up dev or lib release those versions won't work. 
It's a function that connects to a mongoDB and retrieves of all the documents in a collection.

I'm not sure if the error message will help provide more details as to why it works in localhost and not otherwise but here it is.

{
    "error": {
        "type": "RuntimeError",
        "message": "Critical Error: Error: invalid ObjectId, ObjectId.id must be either a string or a Buffer, but is [{\"_base64\":\"WrwQ0+UekAAInZHm\"}]\n    at ObjectID.toHexString (/var/task/node_modules/bson/lib/bson/objectid.js:93:11)\n    at ObjectID.toJSON (/var/task/node_modules/bson/lib/bson/objectid.js:208:15)\n    at JSON.stringify (<anonymous>)\n    at Domain.criticalExecution.run ([eval]:103:45)\n    at Domain.run (domain.js:242:14)\n    at callback ([eval]:83:23)\n    at func.index.apply.params.concat ([eval]:216:51)\n    at cursor.toArray (/var/task/functions/read.js:26:5)\n    at args.push (/var/task/node_modules/mongodb/lib/utils.js:404:72)\n    at handleCallback (/var/task/node_modules/mongodb/lib/utils.js:128:55)"
    }
}

**Comment by jacoblee93** [comment]
Hey @Chinaski1979 !

It looks like it's an error that mongo is throwing - the type field of your error is RuntimeError and at the bottom of your stack Trace I can see `node_modules/mongodb`. From the error message, it seems like the ObjectId you're passing to MongoDB is the wrong type. I can think of a few things to check off the top of my head:

Are you using the same environment variables locally as in dev/release environments?

Are you passing in the same parameters to your function locally as in dev/release? If you have type `any` for a param or have removed the faaslang comment definitions above your function, it's possible that the parameters you pass in are being parsed differently.

In the same vein, how are you calling your function locally vs in dev/release?

Jacob

**Comment by Chinaski1979** [comment]
Hey @jacoblee93 .

I'm using the same env variables across all environments.
I'm passing the same parameter.

I'm testing with postman.
So for example, the version that works perfectly (localhost):

GET: localhost:8170/wepass-services/database/read/?collection=properties

And this is how would call dev for instance:

GET: https://wepass-services.lib.id/database@dev/read/?collection=properties

I really don't get why I get that specific error just for being in different environments.

Thanks for your help.

**Comment by jacoblee93** [comment]
Can you try testing with cURL instead or using the `lib` package as something like:

Node:
```
lib['wepass-services.database[@dev]'].read({collection: properties})
```

CLI: 
```
$ lib wepass-services.database[@dev].read --collection <JSON stringified value>
```

**Comment by Chinaski1979** [comment]
@jacoblee93 I tried that with no luck mate.

**Comment by keithwhor** [comment]
@jacoblee93: The issue is somewhere in the way we handle `Buffer` conversion when connecting functions to each other. It has nothing to do with the way the functions are called or where they're called from.

@Chinaski1979: Can you show me the code that's throwing this error? You can join our Slack channel and DM me directly (go to https://stdlib.com and click on "Slack" from the community dropdown when you're logged in) or copy and paste here. Obviously no need to share anything proprietary; just need to see what you're doing in code.

**Comment by j4orz** [comment]
I'm experiencing this issue as well @Chinaski1979.

Here's a temporary workaround that's quite hacky:

`return callback(null, JSON.parse(JSON.stringify(data)));`

where data is data queried from mongoose.

**Comment by keithwhor** [comment]
This is a super not-fun error that required some digging on our part; we're happy there's a temporary fix but will look at something more permanent shortly.
