### ISSUE TITLE
Debugging with inspect mode

### ISSUE THREAD

**Issue by omarchehab98** [stdlib/lib#144]
If `node` is ran with the `--inspect` switch, then you can connect a debugger and step through your programs.

[Read more about inspector](https://nodejs.org/en/docs/inspector)

**Comment by omarchehab98** [comment]
How about adding an `--inspect` switch to `lib http`?

**Comment by keithwhor** [comment]
Hey @omarchehab98 -- I'm going to tag this as an enhancement. I can look into this, but it might be a little out in terms of implementation.
