### ISSUE TITLE
Decrease timeout field minimum

### ISSUE THREAD

**Issue by omarchehab98** [stdlib/lib#146]
`Bad Request: The "stdlib" timeout field must be between 5,000 and 300,000`

If I know my function's green path terminates fast, it's reasonable to have a short timeout. In cases of 
error, I wouldn't want my function to hang, especially given the fact that every compute second is billed. I experienced function hanging with mongo connection timeout (default 30,000ms).

I think the timeout field should be decreased.

**Comment by keithwhor** [comment]
I'm not sure this is a "bug" or something we'd like to fix. It's pretty common for our developers to rely on chained HTTP calls that can eat up 5,000ms relatively quickly. Having 30,000ms as the default for newly created projects makes sure nobody is going to run into a timeout issue for run-of-the-mill use-cases, but is still configurable.
