### ISSUE TITLE
document lower casing of headers field

### ISSUE THREAD

**Issue by macdja38** [stdlib/lib#147]
It would be nice to see the lower casing of header keys be documented here:

https://docs.stdlib.com/main/#/creating-services/the-context-object

**Comment by keithwhor** [comment]
We can certainly do this. 👍 

cc @jacoblee93 who handles most of our website docs

**Comment by keithwhor** [comment]
@jacoblee93 is this documented yet?

**Comment by jacoblee93** [comment]
Will do this now!

**Comment by jacoblee93** [comment]
Ok, I've added an example to https://docs.stdlib.com/main/#/creating-services/the-context-object. Let us know if there's anything else we can make clearer!

**Comment by macdja38** [comment]
Awesome, thank you very much!
