### ISSUE TITLE
Request service via GET

### ISSUE THREAD

**Issue by ghost** [stdlib/lib#15]
Will it be possible to call my function via GET? Some apps, like podcasts agregators and rss readers, can only make get requests.

**Comment by keithwhor** [comment]
You can --- query parameters map to `params.vflags` 1:1.

Note that by default, it's an array with items separated by spaces (as passed in). This can be overcome using quotation marks.

i.e.

```
https://f.stdlib.com/me/ns/f?name=Hello%20World
```

Maps to

```
params.vflags.name; // -> ['Hello', 'World'];
```

And

```
https://f.stdlib.com/me/ns/f?name="Hello%20World"
```

Maps to

```
params.vflags.name; // -> ['Hello World'];
```
