### ISSUE TITLE
Best practices with env.json

### ISSUE THREAD

**Issue by aaronshaf** [stdlib/lib#151]
I use [vaulted](https://github.com/miquella/vaulted) to enter an environment-specific secure shell, loaded with different environment variables.

I'd rather not put my release/prod env variables in env.json. Any tips?

**Comment by keithwhor** [comment]
Hey @aaronshaf -- I haven't used `vaulted` myself, but we'll definitely consider support. Right now `env.json` is the preferred way of setting environment key/value pairs, if you can get `vaulted` to support writing to that file in a directory it might be the best way to do so for now. We'll likely make updates to this flow in the coming months: I can keep you posted.
