### ISSUE TITLE
npm complain about vulnerabilities with template vue

### ISSUE THREAD

**Issue by astralcai** [stdlib/lib#156]
When I try to create a web app using the Vue template by running:
`lib create my-service -t vue`
The creation succeeded, however npm reports:
`found 5 vulnerabilities (1 low, 4 moderate)`

When I run `npm audit` in the project directory, it shows 5 vulnerabilities of "prototype pollution" with the hoek package, dependency of node-sass #

**Comment by keithwhor** [comment]
We have no intention of upgrading the Vue template at present time, so I'm closing this for now. You can try upgrading the `node-sass` package if you're using it. :)
