### ISSUE TITLE
How can I use node.js modules?

### ISSUE THREAD

**Issue by lorenzoferrante** [stdlib/lib#16]
Hi, it might be a simple issue, but including dependencies in package.json just doesn't work for me. How can I do it? Thanks.

**Comment by keithwhor** [comment]
Hey Lorenzo, sorry I must have missed this when you opened it. :) What exactly is the problem? Where are you adding dependencies and what's not working? If it's in your development environment you'll need to run `npm install` locally.

**Comment by lorenzoferrante** [comment]
Hi, thanks for the answer. My is that when I include the dependencies in `package.json` and try to run `stdlib f:compile` the console returns me this error: `Error: not found: git`.
Then I tried to run `npm install` and remove the dependencies from `package.json` and it doesn't give me any errors, but when I try to execute the function from the terminal or HTTPS it gives this error: `Error: Error: Cannot find module 'module_name'`. What is my problem?
Thank you.

**Comment by keithwhor** [comment]
Hey Lorenzo, are you trying to install directly from a git repository?

**Comment by lorenzoferrante** [comment]
Hi, 
No I'm not installing from a git repo, I just add the name of the module and then run npm install. 
I'm not installing from git because for example Firebase for node does not have a repo.

**Comment by keithwhor** [comment]
Can you show me your `package.json` file?

**Comment by lorenzoferrante** [comment]
Yes of course.

``` javascript
{
  "name": "lorenzoferrante/dev/firebase",
  "version": "1.0.0",
  "main": "index.js",
  "author": "Lorenzo Ferrante",
  "dependencies": {
    "firebase": "^3.4.0"
  }
}
```

**Comment by keithwhor** [comment]
Hey, can you try your project again with the latest version of stdlib and let me know if you're still having trouble?

**Comment by keithwhor** [comment]
Just checking in --- will close this for now unless you have another issue.
