### ISSUE TITLE
'Bad Request: could not update cache'

### ISSUE THREAD

**Issue by nicolocarpignoli** [stdlib/lib#160]
Hi
I used your project to set up a simple slack bot. Today I occured in an error: anytime I do `lib up dev` I got this:

```
2018/08/10 14:26:45.871 [<bot-name>] Bad Request: Could not update cache
Error: There was an error processing your request, try logging in again.
```

Already tried to logout and login with no luck. 

thanks in advance

**Comment by jacoblee93** [comment]
Hi @nicolocarpignoli , 

Thanks for bringing this to my attention. It should work now, please let me know if you encounter an error like this again.

**Comment by nicolocarpignoli** [comment]
@jacoblee93 thanks! it's working like charm :) thanks for the fast support
