### ISSUE TITLE
Using stdlib behind corporate proxy

### ISSUE THREAD

**Issue by matt6500** [stdlib/lib#161]
Hi, I'm trying to install and use stdlib on a computer behind our corporate proxy and I was able to get it installed by changing my npm proxy settings, but when trying to log in with my stdlib credentials, I get an error that says `Error: Server Unavailable`, and was wondering if there was some way to configure lib proxy settings like I did with npm.

**Comment by jacoblee93** [comment]
Hey @matt6500 ! We now have a way to create, manage, and deploy Standard Library APIs via our online IDE [Code.xyz](https://code.xyz) that might work better for you behind a proxy. Happy to try and help resolve the CLI issue if that doesn't meet you needs -- let me know.

**Comment by panchalkalpesh** [comment]
@jacoblee93 Thanks. That's amazing!
Trying to follow along with this [article](https://medium.com/stdlibhq/build-a-serverless-sms-hub-in-under-7-minutes-with-node-js-stdlib-and-messagebird-7d2d41ecaea6)

Having similar trouble logging in: 
![error](https://user-images.githubusercontent.com/1808686/45240152-98f7c700-b2b5-11e8-80f0-cd8c31cbd64d.PNG)

**Comment by jacoblee93** [comment]
Thanks @panchalkalpesh! It'd be tough to debug without being next to you and having access to your proxy. If it helps, all outbound API requests from the CLI go to api.polybit.com, you could try whitelisting that?

**Comment by keithwhor** [comment]
Closing due to lack of feedback / activity.
