### ISSUE TITLE
pulling(lib get) my service causing error

### ISSUE THREAD

**Issue by vishvajit79** [stdlib/lib#162]
I am trying to pull my source code, but it gives me error. 

Retrieving registry.stdlib.com/vishvajit79/slack-app/package.tgz...

{ Error: ENOENT: no such file or directory, open 'D:\tmp\vishvajit79.slack-app.tgz'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at resource.request.index (C:\Users\vishv\AppData\Roaming\npm\node_modules\lib.cli\cli\commands\get.js:131:12)
    at IncomingMessage.res.on.on (C:\Users\vishv\AppData\Roaming\npm\node_modules\lib.cli\node_modules\api-res\module.js:181:22)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\tmp\\vishvajit79.slack-app.tgz' }
Error: Could not write temporary file /tmp/vishvajit79.slack-app.tgz

**Comment by jacoblee93** [comment]
@vishvajit79 , this should be good now! Upgrade your CLI version (`npm i -g lib.cli`) and give it another shot.

**Comment by vishvajit79** [comment]
I updated the CLI version but still gets an error. 

$ lib get vishvajit79/getsense

Retrieving registry.stdlib.com/vishvajit79/getsense/package.tgz...

Error: undefined

**Comment by jacoblee93** [comment]
Can you create a fresh service from the CLI using `lib create`, then run `lib up dev` and see if that works?

**Comment by mannyyang** [comment]
I'm having the same issue and when I tried your recommended steps:
1)  `lib create servicetest`
2) `lib up dev`

It gives me:
Error: Invalid package.json

The newly created package.json:
```
{
  "name": "servicetest",
  "version": "0.0.0",
  "description": "",
  "author": "mannyyang <clearedout@gmail.com>",
  "main": "functions/__main__.js",
  "dependencies": {},
  "private": true,
  "stdlib": {
    "build": "faaslang",
    "name": "mannyyang/income-verification",
    "timeout": 10000,
    "publish": true,
    "personalize": {
      "keys": [],
      "user": []
    }
  }
}
```

**Comment by jacoblee93** [comment]
Hey @mannyyang! Are you in the service directory when you run `lib up dev`?

The steps should actually be:

1. `lib create servicetest`
2. `cd mannyyang/servicetest`
3. `lib up dev`

**Comment by vishvajit79** [comment]
Hi Jacob,

I was successfully able to create service and push the code to the server
but when I try to lib get, it always shows Error: undefined. Please let me
know if there is a way around also I am using windows machine.
Best,
Vishvajit Kher

**Comment by jacoblee93** [comment]
Hey @vishvajit79, I'm going to have access to a Windows machine on Tuesday. I'll try to reproduce your issue and update you then.

**Comment by jacoblee93** [comment]
Hey @vishvajit79, I've found the issue. You can expect a fix by the end of the day.

**Comment by vishvajit79** [comment]
That's great!

Best,
Vishvajit Kher
+1-647-504-4743

**Comment by jacoblee93** [comment]
Update and give it a try @vishvajit79!

**Comment by vishvajit79** [comment]
Hi Jacob,

It worked! Thanks
Best,
Vishvajit Kher

**Comment by jacoblee93** [comment]
Awesome! Let me know if we can help with anything else :)
