### ISSUE TITLE
Specify request method in CLI

### ISSUE THREAD

**Issue by MonsterDeveloper** [stdlib/lib#165]
Hello. I noticed that when I call `lib .myFunction` CLI sends a `POST` request. Is there any way to specify a method (e.g. `lib .myFunction --method GET`)?

**Comment by jacoblee93** [comment]
Hey @MonsterDeveloper, there isn't -- if you really want to, you can use `lib http` to run it on localhost and cURL, but we recommend not relying on the HTTP request method, and instead thinking of your functions as being called whenever someone hits it with any type of request.

**Comment by MonsterDeveloper** [comment]
Well, I am developing a REST API and if you know, it’s based on request methods. So I want 1 endpoint (/events) and if I send GET request, API returns events, when I send POST, I create a new event. I think it is much easier than /getEvents and /createEvent and semantically right.
