### ISSUE TITLE
Publish key in package.json should be set to false by default

### ISSUE THREAD

**Issue by maxfi** [stdlib/lib#171]
lib version: 4.3.6

The default created `package.json` includes:
```
{
  "stdlib": {
    "publish": true,
}
```

In https://github.com/stdlib/lib#pushing-to-the-cloud it states:

> Note: You'll need to set "publish": true in the lib key of your package.json file to see your service appear in the public registry. It's set to false by default.

**Comment by maxfi** [comment]
Just noticed this in the [docs](https://docs.stdlib.com/main/#/quickstart/command-line-interface):

> Note: By default, services you deploy to release environments will appear in the public registry. Services deployed to development/staging environments will not appear in the registry. You can change this visibility using API permissions.

So there's an inconsistency between the README and the docs. Which one is correct? Thanks.

**Comment by jacoblee93** [comment]
Hey @maxfi, we've deprecated and are in the process of fully removing the `publish` flag, its functionality has been superseded by [API permissions](https://docs.stdlib.com/main/#/access-control/api-permissions). The docs are correct here. 

Happy to answer any other questions!

**Comment by sharafeyen** [comment]
OK so what the fk do I do...

**Comment by keithwhor** [comment]
@sharafeyen You can selectively choose who has access to your API using [API Permissions](https://docs.stdlib.com/main/#/access-control/api-permissions). The flag is deprecated; you can leave it out completely.

@jacoblee93 can you submit a PR to fix the README here?
