### ISSUE TITLE
encoding issues on stdlib.com using word2vec-pure-js

### ISSUE THREAD

**Issue by ghost** [stdlib/lib#175]
only reproducible on stdlib.com, thus a problem on your side.

**Comment by keithwhor** [comment]
Hey @LemonAndroid, we can't fix this without steps to reproduce the bug. Please include them and we will look into it 🙂.

**Comment by ghost** [comment]
and i can't keep up with this service.

**Comment by keithwhor** [comment]
I'm sorry? I don't understand.

**Comment by ghost** [comment]
steps: trz using the word2vec-pure-js npm module from within code.stdlib.com.

**Comment by ghost** [comment]
y u click the mute link @keith :D

**Comment by keithwhor** [comment]
I'm sorry, there's not enough information here for our team to reliably reproduce a bug. If you can give a description of the bug and the exact steps (i.e. a minimal example) to recreate it ourselves we can certainly help. This includes a list of steps for us to follow and / or example code that will generate the bug you're encountering, including expected output and actual (buggy) output.

@notoriaga and / or @jacoblee93 will be able to fix it from there. 🙂Thanks!

**Comment by ghost** [comment]
open code.xyz

add word2vec-pure-js npm package

add file 'test-text8-vector.bin' from lemonandroid/qanda-api repository here on github

load this file via word2vec-pure-js#load(filePath)

try to get similar words via word2vec-pure-js#getSimilarWords('test')

observe that the words returned by word2vec-pure-js#getSimilarWords('test') are wrongly de- or encoded

verify NOT on stdlib, that word2vec-pure-js normally works fine (i did this already, just u might want to do this as well for being sure)

@notoriaga
@jacoblee93

**Comment by jacoblee93** [comment]
It seems to work fine for me: http://jacoblee.lib.id/word2vec@dev/?word=test

Is there something else you're expecting here?

**Comment by ghost** [comment]
No, but why is it not working for my project on stdlib, koma/qanda-api?

**Comment by jacoblee93** [comment]
Oh, I just reread your comment and you tried uploading your code from code.stdlib.com. Yes, I'm seeing `Could not find vector for word test`, is this what you're seeing?

If you just need to get unblocked for now, I tried successfully from the CLI first.

**Comment by ghost** [comment]
The file was working before on code.stdlib.com.

The error message given by you is thrown by w2v-pure-js in case the provided model (test-text8-vector.bin in this case) doesn't have data for the provided word.

**Comment by jacoblee93** [comment]
Odd. Here's the working code I deployed with the CLI:

```
const word2vec = require('word2vec-pure-js');

/**
* A simple "hello world" function
*/
module.exports = async (word = 'test') => {
  word2vec.load('./test-text8-vector.bin');
  let result = word2vec.getSimilarWords(word);
  return result;
};
```
The output is: `["testing","tests","stoppage","tested","upshot","termination","piggyback","primality","flight","standby"]` (https://jacoblee.lib.id/word2vec@dev/)

And I'm using `"word2vec-pure-js": "0.0.2"`

Is this the way you expect it to be used?

**Comment by jacoblee93** [comment]
I just tried the above successfully on code.stdlib.com as well, I think I may have had a typo in my initial attempt, especially if the error I was getting was different from what you're seeing.

**Comment by ghost** [comment]
I will try deploying from WLinux/WSL.

**Comment by ghost** [comment]
The result observable here: https://qanda-app.com/.

There is still encoding issues atm.

**Comment by ghost** [comment]
nvm i downloaded the file again and replaced the previous one.

It must have been compromised.

**Comment by ghost** [comment]
gg
