### ISSUE TITLE
Can't publish my lib

### ISSUE THREAD

**Issue by Loruz** [stdlib/lib#176]
My __main__.js looks like this.
```
const puppeteer = require('puppeteer')
module.exports = (html = '', context, callback) => {
  (async () => {
    const browser = await puppeteer.launch()
    const page = await browser.newPage()
    await page.setContent(html)
    const buffer = await page.pdf()
    callback(null, buffer)
    browser.close()
  })()
}
```
I did everything by the book "lib init" "lib create <project>" and when i start "lib up dev"
I get:
2018/11/06 09:54:08.499 [preiksas/puppet-pdf] Uploading... 100.00%
2018/11/06 09:54:08.499 [preiksas/puppet-pdf] Extracting package contents (size 4754)...
2018/11/06 09:54:08.502 [preiksas/puppet-pdf] Registering compiled package...
2018/11/06 09:54:08.502 [preiksas/puppet-pdf] Uploading compiled package...
2018/11/06 09:54:09.545 [preiksas/puppet-pdf] Installing package dependencies...
2018/11/06 09:54:26.946 [preiksas/puppet-pdf] Server Error: There was a problem installing your dependencies
Error: There was an error processing your request, try logging in again.

It seems that these lines missing "Authenticated as <name>" but I can'f figure it out. Maybe there are some other issues ?

**Comment by keithwhor** [comment]
Hey @loruz, we actually don't support `puppeteer` as a package right now -- there are a few issues with installing packages that require large binary installations. We'll work on making the error message clearer.

If you don't mind me asking, what's your goal with using puppeteer? (i.e., what are you trying to take screenshots of?) We may have another solution for you available shortly.

**Comment by Loruz** [comment]
Hey! It's for Invoice pdf generating. Other solutions for pdf that I found were mixing up some styling, and puppeteer seems to work fine with that. I already used stdlib for other pdf generating tool, but I guess it was not as large in binary lol.
