### ISSUE TITLE
HTTP POST request on stdlib function returns ParameterError

### ISSUE THREAD

**Issue by alihaghani** [stdlib/lib#179]
I'm passing parameters in a POST body according to this [FaaSlang example](https://github.com/faaslang/faaslang#what-is-faaslang).

```
{
    "chores": [
        {
            "title": "Task 1"
        },
        {
            "title": "Task 2"
        }
    ],
    "members": [
        {
            "name": "Member 1",
            "phone": "16040000000"
        }
    ]
}
```

However, I get the following:
```
{
    "error": {
        "type": "ParameterError",
        "message": "One or more parameters provided did not match the function signature",
        "details": {
            "chores": {
                "message": "required",
                "required": true
            },
            "members": {
                "message": "required",
                "required": true
            }
        }
    }
}
```

This function endpoint works fine with GET parameters, however, we're having issues sending some arrays as a GET param using Swift.

**Comment by notoriaga** [comment]
Hey @AliHaghani, would you mind providing a small code sample?

**Comment by alihaghani** [comment]
[This](https://github.com/AliHaghani/Abode/blob/master/functions/initializeHome.js) is the function/endpoint.

**Comment by notoriaga** [comment]
Oh sorry, I meant the calling code. What you have looks good for the endpoint. Is it possible you're not setting the Content-Type of your request to 'application/json'?

**Comment by alihaghani** [comment]
Got it. I'm doing a POST from Postman with the body as follows:
```
{
    "chores": [
        {
            "title": "Task 1"
        },
        {
            "title": "Task 2"
        }
    ],
    "members": [
        {
            "name": "Member 1",
            "phone": "16040000000"
        }
    ]
}
```

I also have a header key `Content-Type` with the value `application/json` as well as a `token` in the header. Is my request body malformed?

**Comment by notoriaga** [comment]
I think I got an example working in postman. Go to File -> Import -> Paste Raw Text and enter the following - 

```
{
	"info": {
		"_postman_id": "c1cb1c4c-b668-467a-9661-e24cb4c62ca3",
		"name": "example",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "post example",
			"request": {
				"method": "POST",
				"header": [
					{
						"key": "Content-Type",
						"name": "Content-Type",
						"value": "application/json",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\n  \"chores\": [\n    {\n      \"title\": \"Task 1\"\n    },\n    {\n      \"title\": \"Task 2\"\n    }\n  ],\n  \"members\": [\n    {\n      \"name\": \"Member 1\",\n      \"phone\": \"16040000000\"\n    }\n  ]\n}"
				},
				"url": {
					"raw": "http://alihaghani.lib.id/abode@dev/initializeHome/",
					"protocol": "http",
					"host": [
						"alihaghani",
						"lib",
						"id"
					],
					"path": [
						"abode@dev",
						"initializeHome",
						""
					]
				}
			},
			"response": []
		}
	]
}
```

Let me know if that works!

**Comment by alihaghani** [comment]
~That's odd, the exact same code deployed locally with `lib http` gives the `ParameterError` whereas when deployed to dev with `lib up dev`, it seems to work fine.~

Nevermind, I was missing the trailing `/` in the Postman local URL... Thanks.
