### ISSUE TITLE
Cleaning the function library by removing all /dev/hello functions

### ISSUE THREAD

**Issue by arnaudgs** [stdlib/lib#18]
You should clean the library, or delete /dev/hello functions after a limited time avec their creation.

There are 32 pages of /dev/hello functions :(

**Comment by keithwhor** [comment]
Hahah. There are a lot due to onboarding. A better solution moving forward will likely be to just set `dev/hello` functions to `private`. We'll look into updating that within the week.

**Comment by keithwhor** [comment]
We've updated the registry and removed the onboarding from the beta, which has cleaned everything up. :) Enjoy!
