### ISSUE TITLE
lib up dev throws "access token is invalid" error

### ISSUE THREAD

**Issue by charmingtoad** [stdlib/lib#180]
I used to be able to publish my service with `lib up dev`, but lately instead I get this error: 

Bad Request: Your access token is invalid.
Error: There was an error processing your request, try logging in again.

I have double-checked that the STDLIB_TOKEN in my env.json file matches my library token on stdlib.com, and I'm not sure what else it could be referring to.

**Comment by keithwhor** [comment]
Hey Linda! Try using “lib login” to reauthenticate, it should solve your problem.

Let me know if that works :)

**Comment by charmingtoad** [comment]
Oh, that did it! Thank you very much!
