### ISSUE TITLE
Calling slack Webhooks on external event

### ISSUE THREAD

**Issue by agarwalankitn** [stdlib/lib#181]
I am trying to build a simple bot which post a message into a slack channel based on some external event. For example, I would like to post that "Task X is complete". I am trying to use webhooks for this purpose but I am not sure how to trigger the webhook from my stdlib service. 
I am able to do it based on slack command and get a response but I would like the service to check the status at a fixed interval and once status is complete, post the message to the channel. How can I achieve this in stdlib service?

**Comment by jacoblee93** [comment]
Hi @agarwalankitn,

When you say you are trying to use webhooks, do you mean Slack's incoming webhook system?

If you're looking to trigger your Standard Library API at a fixed interval, you can check out our scheduled tasks system from code.stdlib.com under the *Tasks* pane in the top left.

Also, I'd recommend joining our Slack help channel for more in-depth support -- you can get an invite on stdlib.com under the *Community* tab in the top bar. We're all quite active there!

Best,
Jacob

**Comment by agarwalankitn** [comment]
Thanks @jacoblee93 for such a timely response. Yes, I meant Slack's incoming webhook. I will try out Tasks, I think that will solve the problem. Thanks!
