### ISSUE TITLE
New Function button not working on website

### ISSUE THREAD

**Issue by crazy4groovy** [stdlib/lib#19]
Under the "Your Functions" tab, the "New Function" button brings up a window, but nothing I do can create a new directory and/or function.

**Comment by crazy4groovy** [comment]
Ah, looks like maybe a page refresh error... I finally see a new function after clicking around awhile.

**Comment by crazy4groovy** [comment]
Can't make a new env folder though..?

**Comment by keithwhor** [comment]
You can only modify production environment variables using the CLI right now.

```
stdlib f:env --set <key> <value>
```
