### ISSUE TITLE
Permission to send an SMS has not been enabled for the region indicated by the 'To' number

### ISSUE THREAD

**Issue by nagyv** [stdlib/lib#191]
Hi,

I would like to send a message to my Hungarian number, but I'm not allowed to do it.

This is Twilio setting.

**Comment by shovelend** [comment]
Hey, 

We're facing the same problem in our app when using the utils/sms service. Is it possible to change the Twilio setting on our end or is it done by the Utils team?

Thanks, 
Attila

**Comment by nagyv** [comment]
Just as an idea, if SMS is not crucial for you: I ended up writing a Telegram bot to send out the notifications.

**Comment by keithwhor** [comment]
Hey! Apologies for the delay in following up here -- we're working on a Twilio Connector API that should help solve these problems for you. @notoriaga is planning on a release this month.

In the meantime, would you mind joining our Slack community? You can request an invitation by visiting https://docs.stdlib.com/ and clicking "Request Slack Community Invitation" on the right. We may be able to get you using the Twilio Connector API ahead of release and help you solve your problems!

**Comment by shovelend** [comment]
@keithwhor Hello! Thanks for getting back quickly. Is there any news on the Twilio Connector API? We're receiving reports that some texts are not being sent.

I also requested to join the community but did not see any news there. Is there a way to use the API ahead of release? 
Thank you in advance!

**Comment by keithwhor** [comment]
Hey @shovelend! We've added first-class Twilio support.

https://stdlib.com/blog/announcing-twilio-events-and-connector-api

You'll have to be a paying Twilio user to make use of it effectively, but other than that it should be all good! Please let us know if you have any questions. You can drop by our community Slack by visiting https://docs.stdlib.com and clicking "Request Invitation" on the right.

**Comment by jacoblee93** [comment]
Hey @shovelend, we actually need to add a way to specify a country for purchased phone numbers -- we'll get to this shortly.

**Comment by notoriaga** [comment]
Hey @nagyv if you go on [Build on Standard Library](build.stdlib.com) you can link your own Twilio account. As of right now you can still only purchase US phone numbers. But you can then go to your [Twilio console](https://www.twilio.com/console/sms/settings/geo-permissions) and enable SMS to Hungary.

We are still looking at adding support for buying numbers for other countries but this should work in the meantime.

**Comment by Eugeniochiau** [comment]
### 

> [`_****_`](

- url

)
