### ISSUE TITLE
Creating service from existing dev release of own account

### ISSUE THREAD

**Issue by monis0395** [stdlib/lib#195]
Hi,

I am trying to get my API Library which are currently in dev env

How can I get that?

I tried typing

```
>lib create -s @monis0395/createfeed/dev

Awesome! Let's create a stdlib service!
We'll use the sourcecode @monis0395/createfeed/dev to proceed.

? Service Name createfeed

Retrieving sourcecode @monis0395/createfeed from:
  registry.stdlib.com/~src/@monis0395/createfeed/dev/package.tgz ...

Error: Not found: monis0395/createfeed@dev
```

Is it possible to get it?

PS: the service is currently private

**Comment by jacoblee93** [comment]
Hi @monis0395! You'll actually want to run this command from within your Standard Library directory (the same one you ran `lib init` in, requires you to log in):

`lib get monis0395/createfeed@dev`

That will retrieve your source code and put in a directory called `monis0395/createfeed@dev`. Let me know if that works for you!

**Comment by monis0395** [comment]
Thanks a lot @jacoblee93, it works :)
