### ISSUE TITLE
f:list - A command to list the functions under a namespace

### ISSUE THREAD

**Issue by txgruppi** [stdlib/lib#2]
Would be nice to have a command like `f:list` to list all the functions under a namespace. I'm not sure if it should only list under your own namespaces, for privacy.

```
$ stdlib f:list txgruppi/dev
txgruppi/dev/hello
txgruppi/dev/anotherfunction
```

**Comment by keithwhor** [comment]
Agreed. Queued up.

**Comment by txgruppi** [comment]
I forgot to connect with the PR, this is done in #3

**Comment by keithwhor** [comment]
Have a couple issues with that PR, will comment on them a bit later today. :) Thanks for submitting!

**Comment by txgruppi** [comment]
Alright :)

**Comment by keithwhor** [comment]
This has been added here: https://github.com/poly/stdlib/commit/fcf89ce79b32daa367560f71cdaebe0b3d6043d6

There were also some server-side changes that needed to be done. The following will work:

```
stdlib f:list <username>
stdlib f:list <username>/<namespace>
stdlib f:list <username>/<namespace>/<name>
```
