### ISSUE TITLE
User must restart the init process if the password is wrong

### ISSUE THREAD

**Issue by tsonev7** [stdlib/lib#202]
Currently, the CLI doesn't respond well when we enter a wrong password during the `lib init` process.
If I enter a wrong password, the cli prompts me to enter a new password, however, the email field value looks reset and I have to re-run the `init` command again.

I've attached a screenshot with the steps described above.

<img width="324" alt="Screenshot 2020-09-30 at 16 43 34" src="https://user-images.githubusercontent.com/3913549/94693687-b08ec600-033c-11eb-8c81-5bd0d3c0ad39.png">

**Comment by jacoblee93** [comment]
Hey @tsonev7, thanks for the report. We'll look into fixing this.

**Comment by jacoblee93** [comment]
Hi @tsonev7, I've patched this issue. Reinstall the CLI to see the change reflected.

**Comment by tsonev7** [comment]
Thanks for the quick response!
