### ISSUE TITLE
stdlib f:compile fails

### ISSUE THREAD

**Issue by cara** [stdlib/lib#21]
Is there any way to debug? I suppose timeout. I'm getting this response:
Error: Unexpected server response:

> <!DOCTYPE html>
>     <html>
>     <head>
>       <meta name="viewport" content="width=device-width, initial-scale=1">
>       <style type="text/css">
>         html, body, iframe { margin: 0; padding: 0; height: 100%; }
>         iframe { display: block; width: 100%; border: none; }
>       </style>
>     <title>Application Error</title>
>     </head>
>     <body>
>       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
>         <p>Application Error</p>
>       </iframe>
>     </body>
>     </html>

**Comment by keithwhor** [comment]
I just deployed a function successfully, will look in logs, any chance you can share your `package.json` details?

**Comment by keithwhor** [comment]
We've changed package registration completely and this should no longer be an issue :)
