### ISSUE TITLE
 Password must consist of only A-Z, 0-9 and -

### ISSUE THREAD

**Issue by nemisj** [stdlib/lib#22]
Guys, i would like to use your service, but it makes no sense to me why these are the restrictions on the password. Can it be changed?

**Comment by keithwhor** [comment]
Are you sure you're not getting that error for `username` and not `password`? We don't have restrictions on the password character set.

**Comment by nemisj** [comment]
@keithwhor you're right, sorry, my apologies, didn't look carefully at the error message
