### ISSUE TITLE
How to setup local development without internet

### ISSUE THREAD

**Issue by mmacedoeu** [stdlib/lib#27]
I would like to serve f in my localhost 8080 environment without using stdlib gateway eg. offline.
Do I need to setup nodejs hosting/gateway/bridge myself and call f functions or there is something already done ?

**Comment by keithwhor** [comment]
`f` functions can be executed without having to run your own HTTP server. If you want to access them from a browser, I recommend using `lib up dev` to push them to a live, remote development space and testing them that way. :)
