### ISSUE TITLE
--set password prompting for password

### ISSUE THREAD

**Issue by jimt** [stdlib/lib#28]
It would be nice if `lib user --set password` prompted for a password if one is not supplied on the command line. This would prevent the password from appearing in my shell history.

**Comment by keithwhor** [comment]
Good catch. I'll queue this up for the next minor release and let you know when it's in.

**Comment by keithwhor** [comment]
Alright, this is in as of https://github.com/poly/stdlib/commit/6656838f692dbd680f1b0c86b4b4a12c6ced1626

Version `1.0.4`. Use `--new-password` instead of `--set password <value>`. :)

Cheers,
- Keith
