### ISSUE TITLE
"no env.json detected message" appears when invoking f from a different directory

### ISSUE THREAD

**Issue by thisdavej** [stdlib/lib#29]
When invoking a service using `f` (example: `f thisdavej/test`) from a different directory than my microservice directory, a warning message appears indicating that "no env.json detected".

I recognize the intent of this message; however, I think the most common use case for `f` will be users invoking `f` from the command line to utilize various microservices—and this error message will not be meaningful to them, and will be a distraction.

I'm thinking the error message only makes sense when invoking microservices on the local machine using `f .` and thus the message should not appear otherwise.  If there are other contexts where it is useful, perhaps you could include a `--verbose` flag that could be used by developers for troubleshooting purposes to help guide and notify them that the env.json file could not be found.

**Comment by keithwhor** [comment]
You're right. I will look into changing this behavior, and probably a little bit of the local behavior in general.
