### ISSUE TITLE
Ability to update env.json without having to increase package version

### ISSUE THREAD

**Issue by nemo** [stdlib/lib#36]
I think it makes sense to be able to update env.json and env. variables in general without having to edit the package version.

**Comment by keithwhor** [comment]
I'll have to think about it. Destroys the concept of service immutability in the purest sense.

Edit: Also creates entirely new complexity chain around --- which env variables belong with which service version? Every service version you push = entirely new set of env vars to manage. Quickly becomes untenable for at-scale development.

**Comment by nemo** [comment]
I suppose. I'm fairly used to doing it to heroku apps (which just causes a restart). But I suppose it might make sense to keep it that way to keep things obvious.

**Comment by keithwhor** [comment]
Awesome. Will close this for now. May re-approach later.
