### ISSUE TITLE
Just follow the installation process but got an error

### ISSUE THREAD

**Issue by donPuerto** [stdlib/lib#38]
Im using Windows 10 64 bit
![stdlive](https://cloud.githubusercontent.com/assets/9329005/21282940/bdf5534e-c435-11e6-9960-8a7571562b3d.PNG)

**Comment by keithwhor** [comment]
Hey! Try updating to the version I just pushed (`1.0.10`) and let me know if you still run into the issue.

**Comment by donPuerto** [comment]
Thanks...

**Comment by donPuerto** [comment]
Just test  it, same error above. :(

**Comment by keithwhor** [comment]
Upgrade to `1.0.11` and paste the output again?

You can join our Slack channel (https://stdlib.com - click on "Slack") and I can help you directly. :)

**Comment by donPuerto** [comment]
Opps,
![stdlive2](https://cloud.githubusercontent.com/assets/9329005/21283954/57d66bc6-c448-11e6-9563-dd4e12f24416.PNG)

lib http
![stdlive3](https://cloud.githubusercontent.com/assets/9329005/21284003/76ab4c8c-c449-11e6-8f05-2c78b76f768f.PNG)

Also, i want to join on slack, it always say, your were invinted check your email, but i havent received any invitation..

**Comment by keithwhor** [comment]
Okay. I'll have to spin up a VM to test some of this. Give me a little bit of time. :)

**Comment by donPuerto** [comment]
Sure man, can you invite on slack don.puerto@hotmail.com

**Comment by keithwhor** [comment]
Should be fixed as of https://github.com/poly/stdlib/commit/d0b5f62d715675464b4143ae6252f34a4f15f4b6 :)
