### ISSUE TITLE
Where are all the services?

### ISSUE THREAD

**Issue by optikalefx** [stdlib/lib#39]
I'm interested in building and using services with f. But I can't find anywhere a list of already available examples. I would imagine there's a list of services that people have build or that you've built. Where is that list?

**Comment by keithwhor** [comment]
Hey Sean!

You can find publicly published services by visiting the search page; https://stdlib.com/search

It's mentioned in the docs and you can get there by clicking the green search button on the top right of stdlib.com --- but I gather it's not clear enough. We'll work on making the discovery process better :). Thank you!

(Note that you have to set stdlib: publish: true in package.json for a service to be visible, many people just use services internally / unpublished.)

**Comment by optikalefx** [comment]
Ah, yea. You definitely should add a main nav menu for search.  It really helps sell the dream.
