### ISSUE TITLE
Using Environment Variables to Deploy

### ISSUE THREAD

**Issue by aboglioli** [stdlib/lib#40]
I want to deploy my code to `<stdlib>` through TravisCI (or any CI service).

I would need to set the environment variables to do this because I have to set my user. I can do this using a `build.sh` script for example which can receive $USER and $PASSWD from outside, but it's insecure.

Is there any method to use an `$ACCESS_TOKEN` to Deploy?

**Comment by keithwhor** [comment]
Deployments use access tokens by default from the `.stdlib` file in your workspace, can you share the contents of your `build.sh` script and I can help you get it set up properly?

**Comment by aboglioli** [comment]
I saw that. But I don't want to have `.stdlib` in my public repository.

I was thinking if I could set environment variables in *TravisCi* (this isn't public).

**Comment by keithwhor** [comment]
hmmmm. we could probably do that.

let me look into it tonight, I have a few other fixes to push to the CLI and I think this could be a pretty quick addition.

**Comment by aboglioli** [comment]
Great, thanks! Maybe I will help with a Pull Request :+1:

**Comment by progrium** [comment]
Having configuration available that's not part of the source is HUGE. Every practical use case I can think of requires this.

**Comment by progrium** [comment]
Yes, it's very important for auth to be able to be configured via environment. We don't deploy anything manually and all our code is public, so we need to configure secrets via CI environment.

We also need secrets/configuration the app/service/fn uses to be part of the environment and I don't see any way to do that.

**Comment by keithwhor** [comment]
@progrium You can set environment variables without issue. `env.json` is loaded into `process.env` automatically (think `.env`). When testing in a CI environment you can set variables explicitly to `process.env`.

But if I get what you're asking for --- you want your CI tool to be able to handle deployment as well, correct?

**Comment by progrium** [comment]
Yes. Without secrets in version control. So we'd git ignore env.json and build it manually during CI deploy?

**Comment by keithwhor** [comment]
@progrium yep. That's exactly what you'd do. :) Which CI tool are you integrating with? TravisCI? I can put secrets-based deployment on our TODO list.

**Comment by aboglioli** [comment]
@progrium That's a problem with any system deployed through CI, the solution could be to use a configuration file (or `env.json` in this case).

I was asking for a way to pass my stdlib TOKEN with environment variables instead of using `.stdlib`.

Here is an example [surge.sh/help/integrating-with-travis-ci](https://surge.sh/help/integrating-with-travis-ci). They use a generated TOKEN (`SURGE_TOKEN`), so you can use it directly in your CI system with environment variables because I don't want to have my `.stdlib` file in my public repository.

**Comment by progrium** [comment]
CircleCI, but it shouldn't matter. Ideal would be Heroku-style config management, but that might be a lot for you to implement. I don't really look forward to building env.json even though it's simple. Seems unnecessary after using (and building) systems that don't require that.

I can't imagine this would be the last blocker for us anyway, but I'll keep trying as long as you're resolving these. Nice work.

**Comment by progrium** [comment]
@aboglioli Yes, most CI's will have a way to manage environment, which is a Good Enough store for secrets as long as you don't have to print them out (like using them as args to a login command). 

However, if secrets for the app itself have to be stored in the CI environment, that's pushing it, but still maybe reasonable in some cases.

**Comment by aboglioli** [comment]
Ok. Thanks! I think encrypting `.stdlib` would be enough. Or using an environment variable (`STDLIB_TOKEN` for example) and before run build script from my CI system put this in `.stdlib` file:

```bash
# $STDLIB_TOKEN comes from my CI system and it's private (hidden)
echo "Token = $STDLIB_TOKEN" > .stdlib
```
