### ISSUE TITLE
Don't seem to be able to login with cli from behind corporate proxy

### ISSUE THREAD

**Issue by robertson-ja** [stdlib/lib#41]

**Comment by keithwhor** [comment]
Hey! What corporate proxy are you behind, specifically? You can e-mail me at keith [at] stdlib [dot] com and we can help you around that. :)

**Comment by husainkhambaty** [comment]
Hi, did this get resolved? I have a similar issue and need to get around the corporate proxy. However I do not know what proxy we are using. Is there any option that I can provide to get around this?
