### ISSUE TITLE
Cannot pass negative number as a command line parameter value

### ISSUE THREAD

**Issue by thisdavej** [stdlib/lib#43]
I created a simple `adder` function:
```js
module.exports = (params, callback) => {
    const x1 = Number(params.kwargs.x1);
    const x2 = Number(params.kwargs.x2);
    console.log(`x2 = ${x2}`);

    callback(null, x1 + x2);
};
```
I can't figure out how to pass negative numbers in as parameter values.  Here's what I'm trying:
```sh
c:\> lib . --x1 3 --x2 -2
```
The resulting output is:
```
x2 = 0
3
```
`lib` appears to be interpreting `-2` as another parameter rather than as a parameter value for `x2`.  Do I need to escape the `-2` value somehow?

**Comment by keithwhor** [comment]
Should be fixed as of; https://github.com/stdlib/lib/commit/ccee1fe9ef67fd67a658640fd026acd31151bce7

**Comment by thisdavej** [comment]
Works great now - thanks for your help!
