### ISSUE TITLE
Installation issue due to "lib" executable name

### ISSUE THREAD

**Issue by davidklassen** [stdlib/lib#46]
When installing using `npm i -g lib.cli` on mac I got the following error:
```
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "lib.cli" "-g"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path ../lib/node_modules/lib.cli/cli/bin.js
npm ERR! code EEXIST
npm ERR! errno -17
npm ERR! syscall symlink

npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/lib.cli/cli/bin.js' -> '/usr/local/bin/lib'
npm ERR! File exists: ../lib/node_modules/lib.cli/cli/bin.js
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/david/projects/npm-debug.log
```
I think that the name `lib` is to generic and this can happen on other machines as well

**Comment by keithwhor** [comment]
Hey David,

Can you let me know where `/usr/local/bin/lib` is currently pointing? Did you previously install another version of the `lib` package?

**Comment by davidklassen** [comment]
On my machine `/usr/local/bin/lib` is a directory created by `exiftool`.
And I did not have previously installed versions of lib package

**Comment by keithwhor** [comment]
I'm going to close this issue right now - we haven't had anybody else complain about a conflict, but if we do, I'll reassess at that time for sure.

**Comment by michaelcummings** [comment]
I have the same issue. I do use Exiftool as stated above from @davidklassen 

I removed EXIFtool for now and installation works fine, but this is certainly a clash.
