### ISSUE TITLE
Alexa template does not include request validation.

### ISSUE THREAD

**Issue by wkbaran** [stdlib/lib#52]
Amazon is no longer approving skills without request validation so it should be added to the template.

Where are the templates held? Possibly I could add support to it but I don't see anything related to Alexa in the lib cli.

**Comment by keithwhor** [comment]
Thanks for the heads up and for being so proactive! In the interest of not blocking you our team has made some updates so you'll be able to contribute.

Visit https://github.com/stdlib/utils.templates to see the `utils.templates` service code and instructions on how to work with it.

You can run this service locally using `lib http` from the root directory. Make sure you update the StdLib command line tools, `lib.cli`, to the latest version (`2.1.6`). Use:

```
$ lib create -t <template> -d localhost:8170
```

Once you've created `/templates/<template>/_files/` and `/templates/<template>/package.json`.

Let me know if you have any more questions --- submit a PR to that repository when you're done and we can verify + incorporate your template modifications (and feel free to create new ones if you'd like!).

**Comment by wkbaran** [comment]
Thanks. I also found that it's missing the required LaunchRequest handler. I'll give that a shot too.

**Comment by wkbaran** [comment]
I'm currently getting the following error if I try to run 'lib http' from utils.templates:
C:\Users\billb\AppData\Roaming\npm\node_modules\lib.cli\cli\scripts.js:22
    let npmPath = npmPathCommand.stdout.toString().trim();
                                       ^
TypeError: Cannot read property 'toString' of null
    at Object.run (C:\Users\billb\AppData\Roaming\npm\node_modules\lib.cli\cli\scripts.js:22:40)

'npm bin' returns 'C:\Users\billb\utils.templates\node_modules\.bin'
I'm going to keep looking into it tomorrow but let me know if you have any ideas.

**Comment by keithwhor** [comment]
Win issue. What windows version are you running? I will try to fix within the next 24h.

**Comment by wkbaran** [comment]
Windows 10. Could be. It's acting like it's returning async though it's
clearly a synchronous call.

**Comment by wkbaran** [comment]
I've confirmed it's a Windows issue. I have it running on a vm.
Now I'm just a bit confused on using it for development. When I run 'lib http' from utils.templates it says that it is compressing "templates/alexa/_files". If I use http://localhost:8170/ I get template undefined. If I hit http://localhost:8170/alexa I get "Cannot find module '/home/vagrant/utils.templates/f/alexa/index.js.'"
Am I supposed to run 'lib init' and 'lib create..' from /utils.template?

**Comment by jacoblee93** [comment]
Try running `lib init` and `lib create -t alexa -d localhost:8170` from a different directory while you're running `lib http` in /utils.template. You won't actually navigate to localhost:8170 in your browser. 

To test the service your template creates, you can then run `lib http -p <different port number>`. 

Hope that works!

**Comment by wkbaran** [comment]
Ah, got it. Thanks.

**Comment by keithwhor** [comment]
@wkbaran this should be fixed for Windows as of https://github.com/stdlib/lib/commit/b7a102a84490e46c9a9a61172ba4f22b0abe3b99

Let me know if you have any more problems! :)
