### ISSUE TITLE
Merging package.json

### ISSUE THREAD

**Issue by wkbaran** [stdlib/lib#54]
I'm not seeing my template dependencies getting merged in with the main app template's. Are there any known issues? Can you point me to the code that should be doing this?
I've had a hard time tracking it down but I'm going to take another wack at it this evening.

**Comment by keithwhor** [comment]
Can you give me an example of what you're trying to do? I'm not understanding the issue correctly.

**Comment by wkbaran** [comment]
I found the problem. There was a syntax error in my template's package.json.
