### ISSUE TITLE
lib init error

### ISSUE THREAD

**Issue by eorroe** [stdlib/lib#55]
I have no idea why I'm getting this error or how to debug it:
![image](https://cloud.githubusercontent.com/assets/6982605/24055026/e5e736c6-0b14-11e7-93e3-bf451b54fe14.png)

**Comment by keithwhor** [comment]
I'm not sure why `rx-lite` is even in your `node_modules` folder... it's not a dependency of `lib.cli` at all. Can you try `$ npm cache clean`, `$ npm uninstall lib.cli -g` and `$ npm install lib.cli -g`?

**Comment by eorroe** [comment]
Sadly still same error, weird. I've never seen rx-lite either, until I've tried installing `lib.cli`

**Comment by keithwhor** [comment]
Hey @eorroe, I think this is an `inquirer` package issue. We've updated the CLI since you last tried this, can you try one more time? Also can you let me know your OS? (Win10?)

**Comment by eorroe** [comment]
Cool it worked
