### ISSUE TITLE
lib create: Error Bad Request

### ISSUE THREAD

**Issue by zzmmzz777** [stdlib/lib#57]
Hi,

i just fresh install the cli `yarn global add lib.cli`, log in & try to create a project, then get error:

```bash
/tmp/stdlib-workspace $ lib create t

Awesome! Let's create a stdlib service!

Error: Bad Request
```

where can i get detail error info, or enable the verbose mode?

**Comment by jacoblee93** [comment]
Hey ekousp,

Did you run lib init in the stdlib-workspace directory? Otherwise try lib login again and see if that resolves your issue.

**Comment by zzmmzz777** [comment]
tried again, it works now, thanks.

On 6 Apr 2017, at 16:21, Jacob Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey ekousp,

Did you run lib init in the stdlib-workspace directory? Otherwise try lib login again and see if that resolves your issue.

**Comment by jacoblee93** [comment]
No problem! We should make this error message clearer.
