### ISSUE TITLE
Function Setup

### ISSUE THREAD

**Issue by dkhan11** [stdlib/lib#58]
Hi,

I'm trying to understand from the documentation what is the proper way to handle setup/initialization of a new function. For example: It needs to connect to an underlying service, which takes time and I want it to be done just once on init.
Maybe I missed it, but I can't find reference for that. 
Is it possible?

Thanks,
DD.

**Comment by jacoblee93** [comment]
Hi DD,

The easiest way is to run `lib function:create`.

Best,

Jacob

**Comment by dkhan11** [comment]
Ok, thanks!

**Comment by jacoblee93** [comment]
No problem! For future reference, you can see a list of available commands by running`lib help`.
