### ISSUE TITLE
Change HTTP code in node.js

### ISSUE THREAD

**Issue by neocite** [stdlib/lib#59]
How to change the HTTP code in node function?

Example:

```
var requiredField = {
      statusCode: 422,
      body: 'CPF parameter is required'
};
callback(requiredField, null);

######

var redirectToSite = {
      statusCode: 302,
      body: 'www.uol.com.br'
};
callback(null, redirectToSite);
```
Can i help me?

**Comment by keithwhor** [comment]
Hey Neocite, we don't support different HTTP status codes right now. We'll be looking into it for a future release, certainly.

- Keith
