### ISSUE TITLE
How to secure a "function" ?

### ISSUE THREAD

**Issue by jeveloper** [stdlib/lib#6]
I use webtask.io that's part of auth0 and they use bearer token thats passed in the header.

What are your plans securing a call to endpoint?

use case:

person logs in with twitter , needs to process something specific to him/her  , web app makes a call on his behalf.

I am hoping it won't be too complicated with enough developer control.

cheers

**Comment by keithwhor** [comment]
We still need to implement our own security / authentication model as well as support for things like environment variables. I'll keep you posted and have answers for you soon! It will be easy and you'll have plenty of control - I can promise you that. We'll almost certainly be using `bearer` tokens in the `Authorization` header.

**Comment by jeveloper** [comment]
Thanks ! i'll try to contribute in september !
