### ISSUE TITLE
CORS options not set when returning an error.

### ISSUE THREAD

**Issue by psigen** [stdlib/lib#60]
When a service function returns an error, the `stdlib` servers return that response as a code 400 in `text/plain` **without** adding proper CORS headers.  This causes browser libraries to fail to correctly receive any error responses.  The issue seems to be entirely server-side.

----
Consider the following function that returns an error in some situations:
(Code is running at http://pras.stdlib.com/happy@dev/)

**function.json**
```json
{
  "name": "happy",
  "description": "Returns the string 'happy'.",
  "kwargs": { "happy": "Set this to true." }
}
```

**index.js**
```js
module.exports = (params, callback) => {
  // Return an error if happy is not true.
  if (!params.kwargs.happy) {
    return callback(new Error('Happy must be set to "true".'));
  }
  callback(null, 'happy');
};
```

Let's call this function from browser using the `f` library:
```js
// Load f.js in the HTML HEAD.
f('pras/happy@dev')({
  happy: false   // intentionally cause an error
}, (err, result) => {
  console.log(err);
  console.log(result);
});
```

What we see is that when `happy` is set to `true`, the stdlib servers return a response that includes an `Access-Control-Allow-Origin` clause, which makes the response interpretable by the browser.
```
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:Access-Control-Allow-Origin
Connection:keep-alive
Content-Length:54
Content-Type:application/json
Date:Tue, 18 Apr 2017 05:14:45 GMT
X-Stdlib-Environment:dev
X-Stdlib-Time:100
```

When `happy` is set to false, however, the server responds without these headers when it returns the error:
```
Connection:keep-alive
Content-Length:28
Content-Type:text/plain
Date:Tue, 18 Apr 2017 05:15:12 GMT
X-Stdlib-Environment:dev
X-Stdlib-Time:100
```

Without the header, the browser rejects the response entirely as a security violation:

> XMLHttpRequest cannot load http://f.stdlib.com/pras/happy@dev. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 400.

which means that `f` **loses** the server's error message and returns a generic one instead:

> Error: Could not run function.

**Comment by keithwhor** [comment]
Hey @psigen - apologies for taking about a month to get to this. We've just released a new version of the service builder and our execution gateway, based on the [FaaSlang specification](https://github.com/faaslang/faaslang). This should be fixed for new services. (You'll have to update `lib.cli` and create a new service to test.)
