### ISSUE TITLE
Error: No parser found for extension ".json"

### ISSUE THREAD

**Issue by mikesprague** [stdlib/lib#61]
### Error produced on two computers with the following operating systems:
- MacOS Sierra (w/ latest updates)
- Ubuntu 16.04

### Each computer has the same version of Node/npm/lib.cli installed:
- lib.cli v3.0.0-rc9
- Node v7.10.0
- npm v4.6.1

### Details
- I gave the tutorial on the Medium Slack Platform Blog ([Build a “Serverless” Slack Bot in 9 Minutes with Node.js and StdLib](https://medium.com/slack-developer-blog/build-a-serverless-slack-bot-in-9-minutes-with-node-js-and-stdlib-b993cfa15358)) a try.
- I was able to get as far as Minute 5: StdLib Service Creation when I ran into the error.
  - Running `lib create -t slack` worked as expected. 
  - However, inside my `slack-app` directory, running 
    `lib .commands --command /hello --text hey there --channel general` 
    produced the error `Error: No parser found for extension ".json"`.
- Identical error on both operating systems.

**Comment by marc-se** [comment]
Can confirm this error, running node v6.9.5 on MacOS Sierra (w/ latest updates)

**Comment by keithwhor** [comment]
This should fix the issue right now;

Add: `"build": "legacy"` under the `"stdlib"` field in `package.json`.

LMK if you still have trouble. We're pushing a new release by Monday and a release candidate was accidentally published to NPM. (Hence 3.0.0-rc9 for your version.) I thought I tore it down but apparently it's still running as the latest version.

**Comment by marc-se** [comment]
Thanks for your fast reply @keithwhor - it doesn't work for me, but don't worry, I'll wait till the monday release arrives 👍🏼

**Comment by mikesprague** [comment]
That did it! Looking forward to finishing that tutorial and then digging further into stdlib. Thanks!

**Comment by mikesprague** [comment]
@marc-se I know this is stating the obvious, but just in case (since the suggested fix worked for me), if you have the following `"build": "faaslang",` in your `package.json` under the `"stdlib"` field, you should change `faaslang` to `legacy` - versus adding an additional entry.

**Comment by keithwhor** [comment]
@marc-se and @mikesprague --- Update `lib.cli` to `3.0.1` (or newer) and follow the updated instructions on [the Medium article](https://medium.com/slack-developer-blog/build-a-serverless-slack-bot-in-9-minutes-with-node-js-and-stdlib-b993cfa15358).

Should work A-OK now :).

**Comment by prodrammer** [comment]
I'm getting this when attempting to 'lib http' the vue template example at:

https://docs.stdlib.com/main/#/templates/vue

I'm running:
- node 6.10.3
- npm 3.10.10
- lib 3.0.2
- macOS Sierra 10.12.2

If I change the build setting in package.json from "faaslang" to "legacy", 'lib http' works.

@keithwhor: Is the release pushed? Is faaslang supported?

**Comment by jacoblee93** [comment]
@ryanhaney We'll be pushing an updated version of the Vue template to support faaslang very soon. We're in the process of phasing out all of our legacy templates. We will let you know when it's ready!

**Comment by prodrammer** [comment]
@jacoblee93:

I assume the templates that will be updated are located at https://github.com/stdlib/utils.templates.

If so, I can watch that repo. Please confirm. Thanks!

**Comment by jacoblee93** [comment]
Yessir. It should be soon -- the code is ready, we're just combing through it again.

**Comment by aggierunner** [comment]
I'm having this issue now too, but changing build to legacy as suggested above, fixes the json parser error.

Although that fixes the json error, I'm getting a new error when I try to test the function (`lib . HelloWorld`) `Error: Cannot find module '/path/stdlib/myID/alexa/functions/index.js'`

Any suggestions? It looks like index.js is inside a main folder, but something is expecting it to be in the functions directory...

Versions:
- lib: 3.0.3
- nodejs: 6.11.0
- npm: 3.10.10

**Comment by jacoblee93** [comment]
@aggierunner We updated our Vue template to work with FaaSlang, but we still have to update our Alexa template.

Is there a file called __main__.js in your `myID/alexa/functions` directory? If there is, renaming that to `index.js` and removing the context argument from the function may work for a legacy build.

**Comment by blondesalad87** [comment]
@jacoblee93 does the change for the Vue template apply to the Slack template as well?

**Comment by jacoblee93** [comment]
@blondesalad87 yes, it should all work fine now. Let's continue the conversation on the other issue that you opened!
