### ISSUE TITLE
Alexa skill

### ISSUE THREAD

**Issue by cottonsean** [stdlib/lib#63]
I was trying out your build an Alexa skill based on your article on hackernoon.com.  I ran into the following issue when trying to test the skill I typed "lib ." and got the following error:

Error: Invalid package.json in this directory
  any idea of what is happening?

thanks

**Comment by keithwhor** [comment]
Yeah, your `package.json` is malformed (syntax error).

There's actually another issue with the Alexa Skills, we'll be updating the template / guide shortly to match the new [FaaSlang](https://github.com/faaslang/faaslang) specification.
