### ISSUE TITLE
Cannot deploy demo on website homepage

### ISSUE THREAD

**Issue by prodrammer** [stdlib/lib#64]
I get an error when trying to run the demo on the stdlib.com home page. The error is entitled "Deployment Failure" with description 'Bad Request: No "function.json" files found'.

Attached image fully illustrates error. I was logged in with my stdlib.com username 'appology'.

![demo_deployment_error](https://cloud.githubusercontent.com/assets/1445619/26508952/790e985e-420b-11e7-98ec-00d16e73931e.png)

**Comment by keithwhor** [comment]
Thanks for catching this! It's fixed. The testing suite won't allow you to set parameters right now but we'll be updating this to work shortly.
