### ISSUE TITLE
Error retrieving template: slack

### ISSUE THREAD

**Issue by hbakhtiyor** [stdlib/lib#68]
`lib create -t slack`

```
Awesome! Let's create a stdlib service!
We'll use the template slack to proceed.

? Service Name slack-app
Fetching template slack...

Error: Error retrieving template: slack
```

versions:
Node: v8.0.0
lib: 3.0.2

**Comment by jacoblee93** [comment]
Hi @hbakhtiyor,

Are you perhaps behind a proxy or something similar? That can interfere with retrieving templates.

Best,

Jacob

**Comment by hbakhtiyor** [comment]
hi, no,

npm works well

**Comment by jacoblee93** [comment]
I'm unable to repro on my Mac - did you encounter this consistently? Your machine is having trouble talking to our template service for some reason...

**Comment by jacoblee93** [comment]
Could you tell me what OS you're using? That might help narrow down the possible problems.

**Comment by hbakhtiyor** [comment]
in the evening, strangely works :D

**Comment by jacoblee93** [comment]
Good to hear!

**Comment by jacoblee93** [comment]
Let me know if I can help with anything else.
