### ISSUE TITLE
Pasting password for new user creation

### ISSUE THREAD

**Issue by dcrockwell** [stdlib/lib#7]
I expected:
1. The password to be starred
2. The password to be recognized

What happened:
1. The password was shown without stars
2. The password was not recognized
3. A validation error said I need a password greater than 5 characters.

This was on Mac Chrome

**Comment by keithwhor** [comment]
Can you verify that you weren't pasting the password in the `Username:` field instead of the `Password:` field? (It's shown first.)

**Comment by dcardosods** [comment]
Had the same problem. I can't paste a password.

**Comment by dcrockwell** [comment]
@keithwhor It was in the password field for sure.

**Comment by keithwhor** [comment]
Which browser / operating system? This is likely a browser-specific issue (not handling textarea 'onpaste' correctly).

**Comment by dcrockwell** [comment]
@keithwhor El Capitan (OSX) + Chrome Version 52.0.2743.116 (64-bit)

**Comment by keithwhor** [comment]
Apologies for the delay here. We'll get to this during the day tomorrow. :)

**Comment by keithwhor** [comment]
Hey guys, really sorry for the delay, had a bunch of stuff pop up. I can't recreate this on my own. Are you pasting using cmd+v / option-click + paste, or are you using some sort of third-party tool?

**Comment by dcrockwell** [comment]
- I used a password manager the first time to copy to clipboard, then `cmd+v` to paste it.
- The second time I used  `cmd+c` then `cmd+v`.

**Comment by keithwhor** [comment]
I haven't wrapped my head around what's causing this, but have a feeling it's mostly to due with third-party tools.

We'll be pushing updates within the next few weeks to allow signup that's not from the "web command line" which should alleviate this problem.

**Comment by keithwhor** [comment]
We've removed the onboarding CLI from the website for now. Login is done through a normal form now. Hope this fixes your issues :).
