### ISSUE TITLE
lib init not working.

### ISSUE THREAD

**Issue by ashish1dev** [stdlib/lib#70]
stdlib library install perfectly.

`npm install lib.cli -g`

but when i run `lib init` , i get `command not found` error.

Here are the screen shots:

<img width="804" alt="screen shot 2017-06-14 at 4 06 35 pm" src="https://user-images.githubusercontent.com/706456/27140575-82738e6c-5143-11e7-8864-7740bb657209.png">

Even after reloading `source ~./zshrc`, getting same issue: 

<img width="323" alt="screen shot 2017-06-14 at 5 25 04 pm" src="https://user-images.githubusercontent.com/706456/27140574-8273279c-5143-11e7-9f30-a83b44f9d660.png">

Here is my system info 
```
  System Version:	macOS 10.12.5 (16F73)
  Kernel Version:	Darwin 16.6.0
  Boot Volume:	Macintosh HD
```

**Comment by jacoblee93** [comment]
Do any of the other commands work? Try `which lib`, it might be that the `lib` binary isn't in your path for some reason.

**Comment by jacoblee93** [comment]
Also try `lib version`.

**Comment by ashish1dev** [comment]
No it doesn't work.
<img width="267" alt="screen shot 2017-06-14 at 9 07 51 pm" src="https://user-images.githubusercontent.com/706456/27141356-8da62946-5145-11e7-8ec6-1061a7812f08.png">

**Comment by ashish1dev** [comment]
<img width="307" alt="screen shot 2017-06-14 at 9 08 34 pm" src="https://user-images.githubusercontent.com/706456/27141393-a880c2b2-5145-11e7-8f78-ac1079f7006a.png">

**Comment by jacoblee93** [comment]
Hmm yeah it looks like for some reason `npm install -g` didn't add `lib` to your path. I'm not super familiar with zsh but adding `export PATH=/usr/local/cellar/node/6.2.0:$PATH` to your `.zshrc` file might work? You'll have to run `source/.zshrc` afterwards.

You basically want to add the directory that `npm` installed the `lib` binary into to your path, which, based on your first screenshot, looks like `/usr/local/cellar/node/6.2.0`.

**Comment by jacoblee93** [comment]
https://stackoverflow.com/questions/11530090/adding-a-new-entry-to-the-path-variable-in-zsh

**Comment by ashish1dev** [comment]
After adding the `export PATH=/usr/local/cellar/node/6.2.0:$PATH` to `.zshrc` file.

I again did `npm install lib.cli -g`

I now get `permission denied` error, so i tried with sudo but I still get error.

<img width="584" alt="screen shot 2017-06-14 at 9 34 15 pm" src="https://user-images.githubusercontent.com/706456/27142677-5e91f3de-5149-11e7-9ec4-35cec447666b.png">

**Comment by jacoblee93** [comment]
Have you ever installed anything globally with `npm` before? You could try the steps here: https://stackoverflow.com/questions/15843199/globally-installed-npm-packages-not-working

**Comment by keithwhor** [comment]
@ashish1dev Can you try upgrading to Node 6.10.1 or higher and see if you get the same error?

I tried recreating this in oh-my-zsh on my own and couldn't reproduce.

**Comment by keithwhor** [comment]
Closing due to lack of response. Let me know if you still have trouble with this.

**Comment by tony-h** [comment]
I'm had the same error as @ashish1dev on Ubuntu 16.04.2, but upgrading Nodejs to v8 using PPA solved the problem for me: https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/
```
root@testbox:~# node -v
v8.4.0
root@testbox:~# npm -v
5.3.0
root@testbox:~#
root@testbox:~# npm install lib.cli -g
/usr/bin/stdlib -> /usr/lib/node_modules/lib.cli/cli/bin.js
/usr/bin/lib -> /usr/lib/node_modules/lib.cli/cli/bin.js
/usr/bin/f -> /usr/lib/node_modules/lib.cli/cli/bin.js
+ lib.cli@3.1.1
added 52 packages in 4.741s
root@testbox:~# mkdir stdlib-workspace
mkdir: cannot create directory ‘stdlib-workspace’: File exists
root@testbox:~# cd stdlib-workspace
root@testbox:~/stdlib-workspace# lib init

Welcome to stdlib! :)

```
I assume the error is a version issue since apt-get pulls in an older version of Nodejs (v4).  Once I fixed the link issue, init then generated an error. 

Here is the procedure that reproduced the error described by ashish1dev.

1.  Prior to installing, I ran `apt-get install npm`
2. I then tried `lib init`, which generated the error: /usr/bin/env: ‘node’: No such file or directory
3. Several sites recommend creating a symlink: ln -s /usr/bin/nodejs /usr/bin/node https://stackoverflow.com/questions/30281057/node-forever-usr-bin-env-node-no-such-file-or-directory
4. After creating the symlink, the system generated a different error

```root@testbox:~/stdlib-workspace# lib init
/usr/local/lib/node_modules/lib.cli/cli/commands/__nomethod__.js:162
        lib(cfg)[params.name](kwargs, ...args, cb);
```
Full CLI log
```
root@testbox:~# npm install lib.cli -g
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine lib.cli@3.1.1: wanted: {"node":">=6.0.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
/usr/local/bin/stdlib -> /usr/local/lib/node_modules/lib.cli/cli/bin.js
/usr/local/bin/lib -> /usr/local/lib/node_modules/lib.cli/cli/bin.js
/usr/local/bin/f -> /usr/local/lib/node_modules/lib.cli/cli/bin.js
/usr/local/lib
└─┬ lib.cli@3.1.1
  ├── api-res@0.0.8
  ├─┬ async@2.5.0
  │ └── lodash@4.17.4
  ├─┬ chalk@1.1.3
  │ ├── ansi-styles@2.2.1
  │ ├── escape-string-regexp@1.0.5
  │ ├── has-ansi@2.0.0
  │ ├── strip-ansi@3.0.1
  │ └── supports-color@2.0.0
  ├─┬ cmnd@0.2.1
  │ └── colors@1.1.2
  ├─┬ faaslang@0.1.0
  │ ├── babylon@6.18.0
  │ └── uuid@3.1.0
  ├─┬ inquirer@0.11.4
  │ ├── ansi-escapes@1.4.0
  │ ├── ansi-regex@2.1.1
  │ ├─┬ cli-cursor@1.0.2
  │ │ └─┬ restore-cursor@1.0.1
  │ │   ├── exit-hook@1.1.1
  │ │   └── onetime@1.1.0
  │ ├── cli-width@1.1.1
  │ ├─┬ figures@1.7.0
  │ │ └── object-assign@4.1.1
  │ ├── lodash@3.10.1
  │ ├─┬ readline2@1.0.1
  │ │ ├── code-point-at@1.1.0
  │ │ ├─┬ is-fullwidth-code-point@1.0.0
  │ │ │ └── number-is-nan@1.0.1
  │ │ └── mute-stream@0.0.5
  │ ├─┬ run-async@0.1.0
  │ │ └─┬ once@1.4.0
  │ │   └── wrappy@1.0.2
  │ ├── rx-lite@3.1.2
  │ ├── string-width@1.0.2
  │ └── through@2.3.8
  ├── lib@3.0.1
  ├─┬ stream@0.0.2
  │ └── emitter-component@1.1.1
  └─┬ tar-stream@1.5.4
    ├── bl@1.2.1
    ├── end-of-stream@1.4.0
    ├─┬ readable-stream@2.3.3
    │ ├── core-util-is@1.0.2
    │ ├── inherits@2.0.3
    │ ├── isarray@1.0.0
    │ ├── process-nextick-args@1.0.7
    │ ├── safe-buffer@5.1.1
    │ ├── string_decoder@1.0.3
    │ └── util-deprecate@1.0.2
    └── xtend@4.0.1

root@testbox:~# mkdir stdlib-workspace
root@testbox:~# cd stdlib-workspace
root@testbox:~/stdlib-workspace# lib init
/usr/bin/env: ‘node’: No such file or directory
root@testbox:~/stdlib-workspace# lib init
/usr/bin/env: ‘node’: No such file or directory
root@testbox:~/stdlib-workspace# ln -s /usr/bin/nodejs /usr/bin/node
root@testbox:~/stdlib-workspace#
root@testbox:~/stdlib-workspace#
root@testbox:~/stdlib-workspace# lib init
/usr/local/lib/node_modules/lib.cli/cli/commands/__nomethod__.js:162
        lib(cfg)[params.name](kwargs, ...args, cb);
                                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/lib.cli/node_modules/cmnd/lib/command_line_interface.js:97:20
    at Array.forEach (native)
    at CommandLineInterface.load (/usr/local/lib/node_modules/lib.cli/node_modules/cmnd/lib/command_line_interface.js:80:44)
```
