### ISSUE TITLE
lib up fails when using git dependencies

### ISSUE THREAD

**Issue by olivermaldonado** [stdlib/lib#71]
When using npm to install any package dependency directly from git, it works locally but it fails when deploying with:

> Server Error: Error retrieving dependencies from upstream server

Is there any way to fix this?

**Comment by jacoblee93** [comment]
What dependencies did you use? Or is it any deps? I'll try to repro.

**Comment by olivermaldonado** [comment]
As far as I can tell, it won't work with any git dependency. I have only tried with github though, maybe the problem is with them?

Last test I did was creating a new service from scratch:
```
lib create test
```
then inside the service directory:
```
npm i https://github.com/moment/moment.git
lib dev up
```

This is the result
```
Uploading... 100.00%
Authenticated as ....
Compiling package with environment "dev"...
Extracting package contents (size 684)...
Installing package dependencies...
Server Error: Error retrieving dependencies from upstream server
Error: There was an error processing your request
```

This is the package.json
```
{
  "name": "test",
  "version": "0.0.0",
  "description": "",
  "author": "olivermaldonado <some@mail>",
  "main": "functions/__main__.js",
  "dependencies": {
    "moment": "git+https://github.com/moment/moment.git"
  },
  "private": true,
  "stdlib": {
    "build": "faaslang",
    "name": "olivermaldonado/test",
    "timeout": 10000,
    "publish": true,
    "personalize": {
      "keys": [],
      "user": []
    }
  }
}

```

**Comment by jacoblee93** [comment]
Ah yes, that format unfortunately won't work currently. Try installing it as `npm install moment --save`.

**Comment by olivermaldonado** [comment]
OK. I was just using moment as an example. I was trying to use a repo that is not in npm.
It would be useful to have that other option in the future. So currently only published npm packages work. 

Thanks!

**Comment by jacoblee93** [comment]
Agreed. We have it queued up on our roadmap, and will get it out soon!

**Comment by jacoblee93** [comment]
We'll update our docs to reflect this in the meantime.
