### ISSUE TITLE
lib init hangs at password field

### ISSUE THREAD

**Issue by vellum** [stdlib/lib#75]
- When I do `lib init`, I'm able to enter my email address and get a "welcome back" message. 
- However: when I'm prompted for my password, my terminal hangs and I'm unable to type my password or even do a control-c.
- The same thing happens when I enter a new email address to register a new account.
- I had a previous version of lib.cli installed. I tried removing the directories listed in the readme, `npm uninstall`, and `npm install` again — with the same results.
- I'm running node v8.1.0 and npm 5.0.3
- Incidentally, I tried doing a fresh install on a different machine and `lib init` works as expected.

**Comment by keithwhor** [comment]
Hey - is this still an issue on your old machine?
