### ISSUE TITLE
function names can't contain hyphens

### ISSUE THREAD

**Issue by notoriaga** [stdlib/lib#78]
`lib .test-function`

Error: Invalid function name: test-function (test-function.js)
All path segments must be alphanumeric (or -, _) and start with a letter

**Comment by exsmiley** [comment]
This seems to be an issue with faaslang instead: [https://github.com/faaslang/faaslang/blob/70bf181083473f1baaa97c18df40f3eda3db7ef2/lib/parser/function_parser.js#L50](url)
