### ISSUE TITLE
Documentation Errata

### ISSUE THREAD

**Issue by Pokom** [stdlib/lib#79]
In [connecting-service-enpoints](https://github.com/stdlib/lib#connecting-service-endpoints), I believe a snippet of code may have a mistake(or I am being dense, which is always a possibility!). In particular, when running add_double, I get the following output:

```` sh
poko@poko-MS-7A34:~/stdlib-workspace/abuani/kindle-service$ lib .add_double 1 2
Error: undefined/add Not Found
````

I did a console log of context to see why the following string template was returning undefined:

```` javascript
console.log(${context.identifier});
{ name: 'add_double',
  alias: 'add_double',
  path: [ 'add_double' ],
  params: { a: 1, b: 2 },
  remoteAddress: '::ffff:127.0.0.1',
  http: 
   { url: '/abuani/kindle-service/add_double/',
     headers: 
      { 'content-type': 'application/json',
        'x-faaslang': 'true',
        'x-convert-strings': 'true',
        host: 'localhost:8170',
        connection: 'close',
        'transfer-encoding': 'chunked' } },
  keys: null,
  user: null,
  service: 
   { name: 'abuani/kindle-service',
     path: [ 'abuani', 'kindle-service' ],
     version: null,
     environment: 'local',
     identifier: 'abuani.kindle-service[@local]' } }
````

and noticed the identified field was stashed inside of the service attribute. I altered the code slightly like so and got the appropriate results:

```` javascript
const lib = require('lib');

module.exports = (a = 0, b = 0, context, callback) => {
  const { service } = context;
  return lib[`${service.identifier}.add`](a, b, (err, result) => {
    callback(err, result * 2);
  });
};

poko@poko-MS-7A34:~/stdlib-workspace/abuani/kindle-service$ lib .add_double 1 2
6
````
Let me know if you would like me to fork and create a pull request, I'd be more then happy too with a little bit of assistance.

**Comment by keithwhor** [comment]
Thanks! This was fixed by another community member in https://github.com/stdlib/lib/pull/82.

Let us know if you find anything else, happy to accept PRs!

**Comment by Pokom** [comment]
Great thanks! In the future I'll prepare a pr to submit as well if it's just on documentation! I really enjoy the project so far, have some interesting use cases to try out.
