### ISSUE TITLE
Do you use AWS Lambda?

### ISSUE THREAD

**Issue by FGRibreau** [stdlib/lib#8]
Hello team!

Just curious, are you using AWS Lambda underneath? If so, I saw that you were supporting Node 6, do you use a shim like in Apex to make Lambda support it?

**Comment by keithwhor** [comment]
Hey! We certainly run on a Lambda-style microservice architecture, but we have our own solutions that have been developed independently. As of now we are running on AWS (important for developers to know re: uptime).

**Comment by FGRibreau** [comment]
Nice, thanks for your quick response @keithwhor :+1: :)
