### ISSUE TITLE
home page rendering issue in Safari

### ISSUE THREAD

**Issue by shaozi** [stdlib/lib#80]
Hi,

Your home page: https://stdlib.com has the following issue in Safari:

When the banner `Function for <some dynamic thing> in Seconds` dynamically changes, all page got flashed. You can see the black paragraphs flash for fraction of seconds as if they are re-rendered.

**Comment by jacoblee93** [comment]
Will be fixed shortly! Thanks for bringing this up.

**Comment by jacoblee93** [comment]
Should be fixed now, let me know if the issue reappears!
