### ISSUE TITLE
lib up dev package dependency installation failure for Phantom

### ISSUE THREAD

**Issue by ericnograles** [stdlib/lib#93]
Hi guys,

Great job on this, I'm really enjoying hacking on stdlib. Got a bit of a weird case here that I just wanted to bring up.

Just for kicks, I tried to spin up a microservice that uses [Phantom](https://www.npmjs.com/package/phantom) to render webpages as PDF's or images.  However, `lib up dev` seems to fail at the dependency installation.

![image](https://user-images.githubusercontent.com/6023705/31520495-01d4e0aa-af74-11e7-95c8-5ccb7cbfd8ec.png)

I know Phantom is a bit of a weird one since it comes with the actual [`phantomjs-prebuilt`](https://www.npmjs.com/package/phantomjs-prebuilt) binary.  I did try a service with just `phantomjs-prebuilt` and that fails too.

Am I running into some kind of size limit or is there something about Phantom that just doesn't jive well currently with stdlib?

Thanks for the insight on this, looking forward to using stdlib some more!

**Comment by jacoblee93** [comment]
Hi Eric,

Sorry about the delay. Glad you've been enjoying the platform!

We don't yet support npm packages with static binaries - would something like [Puppeteer](https://github.com/GoogleChrome/puppeteer) fit your use case?

**Comment by ericnograles** [comment]
Hey @jacoblee93, yep, I was going to go that route, but I figured I'd ask here for posterity.  Good to know for future reference about static bins.  Thanks for the clarification!

**Comment by jacoblee93** [comment]
@ericnograles this should work now if you still want to give it a try!
